function tests = test_20w_lowq_gap_diagnostic_workflow
tests = functiontests(localfunctions);
end


function testScriptDeclaresGapModelInputsAndOutputs(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_20w_lowq_gap_diagnostic.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_20w_lowq_gap_diagnostic.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, ...
    'b1_enhancement_points_qabs.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    'session_key = "no_PL2_20w_2film"'));
verifyNotEmpty(testCase, regexp(txt, ...
    'primary_qmax_Ainv\s*=\s*0\.040', 'once'));
verifyNotEmpty(testCase, strfind(txt, ...
    '20w_lowq_gap_model_260508'));
verifyNotEmpty(testCase, strfind(txt, ...
    '20w_lowq_gap_model_summary.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    '20w_lowq_gap_model_diagnostic.png'));
end


function testScriptComparesGappedAndZeroGapModels(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_20w_lowq_gap_diagnostic.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_20w_lowq_gap_diagnostic.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, ...
    'linear_E2_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'linear_E2_zero_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'screened_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'screened_zero_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'Delta_meV'));
verifyNotEmpty(testCase, strfind(txt, ...
    'local_fit_linear_E2_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'local_fit_screened_gap'));
end
