function tests = test_b1_physical_fit_enhancements_workflow
tests = functiontests(localfunctions);
end


function testScriptDeclaresFiveRequestedEnhancements(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_b1_physical_fit_enhancements.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_b1_physical_fit_enhancements.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, 'local_bootstrap_ci'), ...
    'The enhancement workflow should compute bootstrap confidence intervals.');
verifyNotEmpty(testCase, strfind(txt, 'local_qrange_stability'), ...
    'The enhancement workflow should scan qmax stability.');
verifyNotEmpty(testCase, strfind(txt, 'local_qjitter_sensitivity'), ...
    'The enhancement workflow should test defocus/q-jitter sensitivity.');
verifyNotEmpty(testCase, strfind(txt, 'local_huber_fit_diagnostic'), ...
    'The enhancement workflow should include a Huber robust fit diagnostic.');
verifyNotEmpty(testCase, strfind(txt, 'local_residual_diagnostics'), ...
    'The enhancement workflow should analyze residual structure.');
end


function testScriptUsesWideQAndDeclaresExpectedOutputs(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_b1_physical_fit_enhancements.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_b1_physical_fit_enhancements.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, 'branch1_points.csv'));
verifyEmpty(testCase, strfind(txt, 'branch3_points.csv'), ...
    'The B1 enhancement workflow must not read B3 point exports.');
verifyNotEmpty(testCase, strfind(txt, '_wideq030'), ...
    'qmax stability should use the available wide-q B1 point exports.');
verifyNotEmpty(testCase, regexp(txt, ...
    'qmax_values_Ainv\s*=\s*\[[^\]]*0\.18[^\]]*0\.20', 'once'), ...
    'qmax scan should extend beyond 0.15 A^-1.');
verifyNotEmpty(testCase, regexp(txt, ...
    'primary_epsilon_bg\s*=\s*4\.5', 'once'), ...
    'The enhancement workflow should keep epsilon_bg = 4.5 for the main result.');

expected_outputs = { ...
    'b1_bootstrap_ci.csv', ...
    'b1_qrange_stability.csv', ...
    'b1_defocus_qjitter_sensitivity.csv', ...
    'b1_huber_robust_fit.csv', ...
    'b1_residual_structure.csv', ...
    'b1_bootstrap_ratio_hist.png', ...
    'b1_qmax_stability.png', ...
    'b1_defocus_sensitivity.png', ...
    'b1_huber_comparison.png', ...
    'b1_residual_structure.png'};

for i = 1:numel(expected_outputs)
    verifyNotEmpty(testCase, strfind(txt, expected_outputs{i}), ...
        sprintf('Missing expected output reference: %s', expected_outputs{i}));
end
end
