function tests = test_b1_physical_fit_analysis_workflow
tests = functiontests(localfunctions);
end


function testScriptDeclaresB1OnlyThicknessConstrainedFit(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_b1_physical_fit_analysis.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_b1_physical_fit_analysis.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, 'branch1_points.csv'), ...
    'The workflow should read B1 point exports.');
verifyEmpty(testCase, strfind(txt, 'branch3_points.csv'), ...
    'The B1 physical analysis must not read B3 point exports.');
verifyNotEmpty(testCase, regexp(txt, ...
    'primary_epsilon_bg\s*=\s*4\.5', 'once'), ...
    'The main result should fix epsilon_bg = 4.5.');
verifyNotEmpty(testCase, regexp(txt, ...
    'epsilon_bg_values\s*=\s*\[1,\s*4\.5,\s*10,\s*15\]', 'once'), ...
    'The workflow should retain the requested dielectric sensitivity bracket.');
verifyNotEmpty(testCase, strfind(txt, 'rho0_2film = r * rho0_1film'), ...
    'The thickness model should explicitly parameterize rho0_2film as r*rho0_1film.');
verifyNotEmpty(testCase, strfind(txt, 'r = 1 + exp'), ...
    'The thickness ratio should be constrained to r > 1.');
end


function testScriptDeclaresExpectedInputsAndOutputs(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_b1_physical_fit_analysis.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_b1_physical_fit_analysis.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, '590_gui_history_area_260506'));
verifyNotEmpty(testCase, strfind(txt, 'n0_PL2_10w_gui_history_area_260506'));
verifyNotEmpty(testCase, strfind(txt, ...
    'no_PL2_20w_2film_gui_history_area_260506_highq_refined'));

expected_outputs = { ...
    'b1_physical_fit_summary.csv', ...
    'b1_physical_fit_points_qabs.csv', ...
    'b1_model_comparison.csv', ...
    'b1_epsilon_bg_sensitivity.csv', ...
    'b1_physical_fit_panels.png', ...
    'b1_residuals.png', ...
    'b1_rho0_thickness_ratio.png'};

for i = 1:numel(expected_outputs)
    verifyNotEmpty(testCase, strfind(txt, expected_outputs{i}), ...
        sprintf('Missing expected output reference: %s', expected_outputs{i}));
end
end
