function tests = test_lowq_gap_comparison_workflow
tests = functiontests(localfunctions);
end


function testScriptDeclaresThreeSessionComparison(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_lowq_gap_comparison.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_lowq_gap_comparison.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, ...
    'b1_enhancement_points_qabs.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    '590_PL2_10w'));
verifyNotEmpty(testCase, strfind(txt, ...
    'n0_PL2_10w_repeat'));
verifyNotEmpty(testCase, strfind(txt, ...
    'no_PL2_20w_2film'));
verifyNotEmpty(testCase, regexp(txt, ...
    'primary_qmax_Ainv\s*=\s*0\.040', 'once'));
verifyNotEmpty(testCase, strfind(txt, ...
    'lowq_gap_comparison_260508'));
end


function testScriptUsesSameGapModelsAs20wDiagnostic(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_lowq_gap_comparison.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_lowq_gap_comparison.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, ...
    'linear_E2_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'linear_E2_zero_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'screened_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'screened_zero_gap'));
verifyNotEmpty(testCase, strfind(txt, ...
    'Delta_meV'));
verifyNotEmpty(testCase, strfind(txt, ...
    'lowq_gap_comparison_summary.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    'lowq_gap_comparison_primary.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    'lowq_gap_comparison_diagnostic.png'));
end
