function tests = test_20w_lowq_sqrt_zero_diagnostic_workflow
tests = functiontests(localfunctions);
end


function testScriptDeclares20wLowQInputsAndWindows(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_20w_lowq_sqrt_zero_diagnostic.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_20w_lowq_sqrt_zero_diagnostic.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, ...
    'b1_physical_fit_enhancements_260507'));
verifyNotEmpty(testCase, strfind(txt, ...
    'b1_enhancement_points_qabs.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    'session_key = "no_PL2_20w_2film"'));
verifyNotEmpty(testCase, regexp(txt, ...
    'qmax_values_Ainv\s*=\s*\[[^\]]*0\.020[^\]]*0\.040[^\]]*0\.0475', ...
    'once'));
verifyNotEmpty(testCase, regexp(txt, ...
    'primary_qmax_Ainv\s*=\s*0\.040', 'once'));
end


function testScriptComparesFreeAndForcedZeroSqrtFits(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_20w_lowq_sqrt_zero_diagnostic.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_20w_lowq_sqrt_zero_diagnostic.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, ...
    'local_fit_sqrt_free_intercept'));
verifyNotEmpty(testCase, strfind(txt, ...
    'local_fit_sqrt_zero_intercept'));
verifyNotEmpty(testCase, strfind(txt, ...
    'free_intercept_ci95_low_meV'));
verifyNotEmpty(testCase, strfind(txt, ...
    'delta_RMSE_zero_minus_free_meV'));
verifyNotEmpty(testCase, strfind(txt, ...
    '20w_lowq_sqrt_zero_summary.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    '20w_lowq_sqrt_zero_diagnostic.png'));
verifyNotEmpty(testCase, strfind(txt, ...
    '20w_lowq_sqrt_zero_report.md'));
end
