function tests = test_lowq_powerlaw_deviation_workflow
tests = functiontests(localfunctions);
end


function testScriptDeclaresPowerlawDeviationInputsAndOutputs(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_lowq_powerlaw_deviation_export.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_lowq_powerlaw_deviation_export.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, ...
    'b1_enhancement_points_qabs.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    '590_PL2_10w'));
verifyNotEmpty(testCase, strfind(txt, ...
    'n0_PL2_10w_repeat'));
verifyNotEmpty(testCase, strfind(txt, ...
    'no_PL2_20w_2film'));
verifyNotEmpty(testCase, regexp(txt, ...
    'primary_qmax_Ainv\s*=\s*0\.040', 'once'));
verifyNotEmpty(testCase, strfind(txt, ...
    'lowq_powerlaw_deviation_260508'));
end


function testScriptExportsFreeAndForcedSqrtFits(testCase)
case_root = fileparts(fileparts(mfilename('fullpath')));
script_path = fullfile(case_root, 'scripts', ...
    'run_lowq_powerlaw_deviation_export.m');

assertTrue(testCase, isfile(script_path), ...
    'case_studies/bisb2026/scripts/run_lowq_powerlaw_deviation_export.m should exist.');

txt = fileread(script_path);

verifyNotEmpty(testCase, strfind(txt, ...
    'free_intercept_meV'));
verifyNotEmpty(testCase, strfind(txt, ...
    'zero_slope_meV_sqrtA'));
verifyNotEmpty(testCase, strfind(txt, ...
    'local_fit_sqrt_free_intercept'));
verifyNotEmpty(testCase, strfind(txt, ...
    'local_fit_sqrt_zero_intercept'));
verifyNotEmpty(testCase, strfind(txt, ...
    'powerlaw_deviation_summary.csv'));
verifyNotEmpty(testCase, strfind(txt, ...
    'powerlaw_deviation_sqrt_comparison.png'));
verifyNotEmpty(testCase, strfind(txt, ...
    'powerlaw_deviation_residuals.png'));
end
