function archive = c20_v4_finish(out)
% Final artifact-driven report. Requires persisted core and P5 checkpoints.
assert(isfile(fullfile(out,'validation','simulation_summary.csv')));
assert(isfile(fullfile(out,'validation','profiles','profile_objective.csv')));
c20_v4_supplement(out);
src={which('c20_v4_supplement'),which('c20_v4_verify_packet'),which('c20_v4_package'),which('c20_packet_readback'),[mfilename('fullpath') '.m']};
rows=cell(numel(src),2);
for k=1:numel(src)
 hash=c20_v4_io('hash',src{k}); rows(k,:)={string(src{k}),string(hash)};
 [~,name,ext]=fileparts(src{k}); copyfile(src{k},fullfile(out,'provenance','source_snapshot',[name ext]));
end
writetable(cell2table(rows,'VariableNames',{'path','sha256'}),fullfile(out,'provenance','finalization_source_hashes.csv'));
parent=jsondecode(fileread(fullfile(out,'provenance','parents.json')));
before=load(fullfile(out,'provenance','parent_hashes_before.mat'));
assert(isequal(before.parent_before{1},c20_v4_io('inventory',parent.v2)));
assert(isequal(before.parent_before{2},c20_v4_io('inventory',parent.v3)));
localcheck=c20_v4_verify_packet(out);
writetable(localcheck.fit_checks,fullfile(out,'tests','persisted_array_checks.csv'));
models=readtable(fullfile(out,'590_PL2_10w','model_comparison.csv'));
pars=readtable(fullfile(out,'590_PL2_10w','component_parameters.csv'));
sim=readtable(fullfile(out,'validation','simulation_summary.csv'),TextType='string');
profiles=readtable(fullfile(out,'validation','profiles','profile_objective.csv'));
solver=readtable(fullfile(out,'590_PL2_10w','solver_background_differences.csv'));
frame=jsondecode(fileread(fullfile(out,'590_PL2_10w','A0_A1_diagnostics.json')));
tests=readtable(fullfile(out,'tests','results.csv')); ts=readtable(fullfile(out,'tests','simulation_tests.csv'));
np=sum(tests.Passed)+sum(ts.Passed); nf=sum(tests.Failed)+sum(ts.Failed);
status=struct('input_validity','raw and JSON SHA256 verified; A0 equals parent L1; both parent trees unchanged', ...
 'parent_boundary_mapping','2592 candidates; 16848 parameter rows; 702 selected rows; zero flag mismatch', ...
 'nominal_bin_geometry','nine same-center bins verified; different N not independent', ...
 'sequence_semantics','camera sequence and exposure documented; fixed sample position and stationarity unknown', ...
 'A1_status','tested_applied_integer_common_shift; 300 valid frames; native support saved', ...
 'numerical_status','36 models and 1008 optimized candidates saved; witness distinct from optimized solution', ...
 'model_adequacy','not statistically validated; structured residuals remain', ...
 'energy_identifiability','not_assessed_statistically','width_identifiability','not_assessed_statistically', ...
 'area_identifiability','not_assessed_statistically','origin_status','not_assessed', ...
 'P5_status','4 scenarios x (10 smoke + 100 pilot); engineering noise only; no experimental false-positive claim', ...
 'profile_status','sparse objective profiles; inspect optimizer flags; not confidence intervals', ...
 'frame_bootstrap','not_run: same-position stability and noise target unverified', ...
 'A1_refitting','not_run; A1 assessed with elastic reference and raw block spectra', ...
 'mirror_bins','not_run','full_q','not_run','physical_fits','not_run', ...
 'new_and_legacy_tests_passed',np,'tests_failed',nf,'parent_unchanged',true);
c20_v4_io('json',fullfile(out,'stage_status.json'),status);
text={ '# C20/B1 v4 actual execution and review', ...
 'This is a new run. The v3 complete labels are not accepted as evidence: v3 lacked new fitted arrays, component mapping, and applied A1. No old run was overwritten.', ...
 '## Inputs and identity', ...
 '590 native NPY/JSON selected by session_id and extension, hashes matched parent manifest before use and raw after use. Native sequence-q-E is 300 x 512 x 1028. Invalid q mask independently reproduced parent column 461; sentinel mechanism is not inferred from its value. Native dtype/header and detector mask maxima are recorded.', ...
 'Camera metadata contains is_sequence, nimages=300, exposure=10 s and frame_time=10 s. Fixed position, per-frame timestamps and sample stability are not verified. Sequence blocks are not presumed independent.', ...
 '## Actual boundary audit', ...
 '108 parent fits / 2592 candidates / 16848 parameter rows / 702 selected rows. Every candidate has its own raw-to-energy-order map and native-unit conversion. All selected native curves and objectives reconstruct. Legacy boundary flags: zero mismatches.', ...
 '98 selected fits have at least one boundary: background r lower in 96, background B lower in 52, r upper in 1, E0 upper in 2. Categories overlap; no selected width or peak-amplitude bound hits. Background boundary does not itself disqualify peak energies, and absence of peak bounds is not identifiability.', ...
 '## Real fitting and saved data', ...
 sprintf('Legacy reconstruction: %d models, %d components, 288 candidates; selected boundary count %d. Mode 2 has independent model streams plus 12 asymmetric weak-component starts for n2. Mode 3 adds a nonnegative constant to BOTH hypotheses. Total: 36 models, 54 component records, 1008 optimized candidates, 18 separate H0 feasible witnesses.',height(models),height(pars),nnz(models.boundary)), ...
 sprintf('Across solver/background comparisons, largest absolute normalized-objective change from legacy is %.6g. This does not establish decomposition uniqueness. Sparse profiles have %d points, %d with no converged optimizer start.',max(abs(solver.delta_Q_vs_legacy)),height(profiles),nnz(profiles.converged_starts==0)), ...
 'All comparisons use the same three N=3 centers, 300-1800 meV, unchanged width bounds and no physical prior. Width columns distinguish native Lorentzian FWHM/DL Gamma from zero-baseline finite-window bracketed widths. Areas refer to Wref=[300,1800] and have ordinate*meV units, not electron counts. Native A is not comparable between DL and symmetric models.', ...
 '## Real frames and A1', ...
 sprintf('A0 native-frame sum versus parent L1: maximum error %.6g. Fixed elastic window [-100,100] meV and reference |q|<=0.001 A^-1 produced %d valid integer offsets. Correction is minus observed offset. Original member spectra, corrected members, support, all shifts, 18 actual block sums and per-frame means are in sequence_block_spectra.mat.',frame.A0_L1_max_error,frame.valid_shift_frames), ...
 sprintf('Reference-band cumulative zero-baseline ZLP FWHM A0/A1: %.6g / %.6g meV. These are sample elastic reference diagnostics, not independent response calibration or intrinsic-width correction. Shift lag1=%.5f, linearly detrended=%.5f: descriptive quantized correlations, not effective independent frame counts.',frame.reference_ZLP_FWHM_A0_meV,frame.reference_ZLP_FWHM_A1_meV,frame.offset_lag1,frame.linear_detrended_offset_lag1), ...
 '## Minimal P5', ...
 'Four named hypothetical scenarios were fixed before trials: static single, q-mixed single, overlapping broad double, background mismatch. Each has 10 smoke draws then 100 different-seed pilot draws. Detector noise was NOT fitted: independent Gaussian noise at 1 percent max ordinate is only an engineering assumption. Simulation search uses 4 independent starts plus 4 n2 extras, explicitly less than the real-data search budget. No experimental false-positive rate or CI is claimed.', ...
 'The predeclared engineering split flag requires relative objective gain >0.1, reference-window component fraction >0.05 and center separation >4 meV. This is NOT a calibrated detection rule. Failures and boundary/collapse are retained. Wilson intervals describe only the hypothetical trial proportion. Generated H0 means never include the observed dual-structure mean or uncentered experimental residual.', ...
 '| Pilot scenario | Trials | Engineering split flags | Failures | n2 boundary |', ...
 '|---|---:|---:|---:|---:|'};
for k=find(sim.phase==2).'
 text{end+1}=sprintf('| %s | %d | %d | %d | %d |',sim.scenario(k),sim.trials(k),sim.engineering_splits(k),sim.failures(k),sim.boundary(k));
end
text=[text,{'## Verification and limits', ...
 sprintf('New contracts (10), simulation-generator tests (2), legacy pilot tests (7): %d passed, %d failed. Separate persisted-array tests recompute 36 fits and 1008 candidates and every actual block. The archive is additionally extracted and checked by the packaging entry; its result is saved alongside the ZIP.',np,nf), ...
 'No full repository test suite was run. The historical overlapping branch-window test is outside this local sorting chain and remains a known unaddressed regression. P5 experiment-calibrated inference, frame bootstrap, dense profile coverage, mirrored-q fits, q/time single-mode mixture exclusion, and physical attribution remain unperformed.', ...
 'Minimum additional information: confirm whether all 300 frames observe the same location and whether beam/sample changes are expected; same-condition elastic/dark references are needed for intrinsic response/noise claims. Existing blocks show ordered shape/intensity changes, so do not blindly iid-resample them.', ...
 'Visual spot checks: actual paired-fit legends and block/A0-A1 plots were rendered and inspected; arrays are the authoritative payload.', ...
 '## Recompute without raw', ...
 'From the project root: addpath(''case_studies/bisb2026/scripts''); result=c20_v4_verify_packet(''<extracted packet folder>'');', ...
 'A full new run is run_b1_component_v4(); it is not required to review this packet. Source snapshots identify core, P5 and finalization stages separately.'}];
c20_v4_io('text',fullfile(out,'run_report.md'),strjoin(text,newline));
archive=c20_v4_package(out);
end
