function archive = c20_v5_finish(out,delivery_name)
if nargin<2, delivery_name=''; end
assert(isfile(fullfile(out,'validation','positive_controls.csv')));
assert(isfile(fullfile(out,'q_center_diagnostics','elastic_profiles.mat')));
before=load(fullfile(out,'provenance','parent_hashes_before.mat'));
for k=1:numel(before.parents), assert(isequal(before.parent_hashes{k},c20_v4_io('inventory',before.parents{k})),'Old run changed'); end
c20_v5_interpret(out); verified=c20_v5_verify(out);
units_table=readtable(fullfile(out,'audit','area_scope_corrected.csv'),TextType='string');
units_table.native_A_unit=repmat("corrected_counts*meV",height(units_table),1);
units_table.native_A_unit(units_table.peak_model=="lorentz")="corrected_counts*meV^2";
units_table.integrated_area_unit=repmat("corrected_counts*meV",height(units_table),1);
writetable(units_table,fullfile(out,'audit','area_scope_corrected.csv'));
directories=dir(fullfile(out,'member_models','R*'));
for k=1:numel(directories)
 file=fullfile(directories(k).folder,directories(k).name,'parameters.csv'); t=readtable(file,TextType='string');
 unit="corrected_counts*meV"; width_name="symmetric_Lorentzian_FWHM";
 if ~contains(directories(k).name,'symmetric'), unit="corrected_counts*meV^2"; width_name="Drude_Lorentz_Gamma"; end
 t.native_A_unit=repmat(unit,height(t),1); t.native_width_definition=repmat(width_name,height(t),1);
 t.integrated_area_unit=repmat("corrected_counts*meV",height(t),1); writetable(t,file);
end
sources=dir(fullfile(fileparts(mfilename('fullpath')),'c20_v5*.m')); rows={};
for k=1:numel(sources)
 src=fullfile(sources(k).folder,sources(k).name); hash=c20_v4_io('hash',src);
 rows(end+1,:)={string(src),string(hash)}; %#ok<AGROW>
 dst=fullfile(out,'provenance','source_snapshot','case_studies','bisb2026','scripts',sources(k).name); copyfile(src,dst);
end
writetable(cell2table(rows,'VariableNames',{'path','sha256'}),fullfile(out,'provenance','auxiliary_source_hashes.csv'));
changed=readtable(fullfile(out,'A0_A1','parameter_changes.csv'),TextType='string'); comps=readtable(fullfile(out,'member_models','competition_summary.csv'),TextType='string');
controls=readtable(fullfile(out,'validation','positive_controls.csv'),TextType='string'); tests=readtable(fullfile(out,'tests','results.csv'));
q=readtable(fullfile(out,'q_center_diagnostics','centroid_sensitivity.csv')); q4=q(q.half_band_channels==4,:);
blocks=readtable(fullfile(out,'sequence_models','block_diagnostics.csv')); low=blocks(blocks.region==1,:);
state=struct('scope','data_constrained_pilot','area','162 component rows; fit vs reference windows separated; no refit', ...
 'A1','12 complete models, paired with existing A0 mode2 on identical support', ...
 'member_models','three regions x two shapes x M1/M2; 12 models and 144 candidates', ...
 'q_center','profiles measured; actual q-zero drift vs profile deformation unresolved; no lateral correction', ...
 'acquisition','same region continuous, no scan/move/beam adjustment: user confirmed 2026-09-12', ...
 'sequence','real A1 block diagnostics; stationarity and independent repeats not established', ...
 'block_single_vs_double_fits','not_run','member_A1_fits','not_run: A0 primary member comparison', ...
 'flexible_M1_width_or_curvature','not_run: requires separately named follow-up', ...
 'controls','3 x 10 engineering positive controls; not experiment-calibrated inference', ...
 'CI_pvalues','not_assessed','physical_origin','not_assessed','old_runs_unchanged',true, ...
 'tests_passed',sum(tests.Passed),'tests_failed',sum(tests.Failed));
c20_v4_io('json',fullfile(out,'stage_status.json'),state);
text={ '# C20 v5: data-constrained competing explanations', ...
 '## Scope and acquisition', ...
 'This run continues the verified v4 packet. No P0-P4 full rerun, whole-q scan, old-output replacement, or physical fit. The user confirmed on 2026-09-12 that all 300 frames are continuous acquisition from the same region, without scanning, changing region or adjusting the beam. This resolves the acquisition-history question, not stationarity or independence.', ...
 'The graduation-thesis baseline treats B1 as a broad low-energy candidate and leaves single broad response versus nearby components unresolved. This run tests limited spectral descriptions, not quasiparticle identity.', ...
 '## Area correction', ...
 'The 162 parent component rows are regenerated from saved selected parameters without refitting. 108 extended-window rows had full-fit-window areas mislabeled as Wref. New columns separate fit-window/reference-window areas, explicit integration support and full-observation flag. Corrected counts times meV are not electron numbers; DL native amplitude differs dimensionally from symmetric Lorentzian amplitude.', ...
 '## A1: can estimated common energy drift explain away the candidate decomposition?', ...
 sprintf('All 12 A1 models are saved with 360 candidates and H0 witnesses. A0 reconstructed inputs match existing mode2. Across the 12 n2 components the maximum native-center shift is %.3f meV and maximum reference-area-fraction change is %.4f. These changes compare the same frame data under a fixed ZLP-derived transformation; they are not independent-replicate errors.',max(abs(changed.delta_E0(changed.n==2))),max(abs(changed.fraction_A1(changed.n==2)-changed.fraction_A0(changed.n==2)))), ...
 'Interpretation: the tested common integer energy drift alone is not a sufficient explanation for the existing two-term envelopes: both line shapes retain similar conditional decomposition after A1. This does not exclude static energy-q tilt, subpixel response, time-varying single-mode states, or line-shape/background dependence.', ...
 '## M1 versus M2: actual member spectra, not repeated bin observations', ...
 'Observations are five native q channels per region, counted once. M1 has one local linearly dispersing center and shared width, per-member positive amplitude and background amplitude, regional power-law exponent. M2 adds a second such component with the identical background freedom. Energy endpoints are bounded to the observed window, widths 4-5000 meV. Slopes are fitted from members, not copied from the 160 meV/channel stress simulation. Ordering is defined at region center; crossing is not prohibited.', ...
 'One regional scalar rescales the solver; no member-wise area normalization or variance weighting. Per-model 12 starts include a saved A0 seed. All candidates, optimality, native centers/slopes/amplitudes, per-member background/components/total/residual, zero-amplitude M1 witness and derived N1/3/5 predictions are saved.', ...
 '| Region / line shape | M1 slope (meV per native channel) | M1 smoothed residual RMS | M2 smoothed residual RMS |', ...
 '|---|---:|---:|---:|'};
for k=1:height(comps)
 text{end+1}=sprintf('| R%d / %s | %.3f | %.4g | %.4g |',comps.region(k),comps.model(k),comps.M1_slope_meV_A(k)*.0005,comps.M1_smooth_residual_RMS(k),comps.M2_smooth_residual_RMS(k));
end
text=[text,{'Smoothed residual RMS uses a fixed nine-sample moving mean only as a descriptive structure diagnostic, never as a calibrated statistic.', ...
 'R1: both line shapes show coherent residual structure across individual members under M1; M2 substantially reduces it, but structured low-energy residuals remain. This supports an effective two-component candidate relative to this restricted M1, not exclusion of every single-mode mixture. Shared-width or linear-center inadequacy is still a competing explanation.', ...
 'R2: the M2 advantage is smaller and line-shape dependent. It is suggestive of additional envelope structure, not decisive evidence against a flexible single mode. R3: member-wise differences are small relative to observed scatter; a single broad local mode remains a viable unresolved competitor.', ...
 'The linear M1 slopes correspond to only a limited observed center change across each five-member region. Their values are conditional on shape/shared width and unweighted fitting. Unknown intra-pixel q acceptance and possible q-center changes are not excluded by resolving five pixel centers.', ...
 '## Elastic q center and sequence evolution', ...
 sprintf('The fixed center +/-4-channel centroid spans %.4f to %.4f native channels, while argmax switches between 235 and 236. Raw and edge-subtracted centroids for several bands, and all 300 elastic q profiles, are saved. A whole-channel argmax switch must not be assigned as a measured one-channel physical q drift.',min(q4.raw_centroid_channel),max(q4.raw_centroid_channel)), ...
 'Interpretation: there is sequence-dependent elastic-profile variation beyond merely reporting an integer peak label, but centroid band/background sensitivity and profile deformation prevent a unique q-zero translation estimate. No q re-alignment was performed.', ...
 sprintf('R1 A1 block-integral range is %.3f to %.3f counts*meV per frame; window spectral centroids span %.3f to %.3f meV. Scale-only block residuals are nonzero and saved. These are descriptive observations from the same continuous acquisition, not six independent experiments.',min(low.area_300_1800_per_frame),max(low.area_300_1800_per_frame),min(low.spectral_centroid_meV),max(low.spectral_centroid_meV)), ...
 'A moving/shape-changing single mode over time has not yet been fitted block by block and cannot be excluded. User confirmation of no deliberate changes does not rule out instrumental drift or specimen evolution. No iid bootstrap or experimental CI was run.', ...
 '## Positive controls', ...
 sprintf('Correct-background B1 applied to the same 10 saved background-mismatch smoke datasets gives %d/10 legacy split flags (previous B0 smoke was 10/10). This directly demonstrates the artificial envelope can arise from omitted constant background in that known synthetic scenario; it is not a recalculation of the former 94/100 pilot.',nnz(controls.legacy_engineering_split_not_detection(controls.scenario=="background_correct_B1"))), ...
 'The known q-mixed single-mode case is recovered at member level in 10 fresh engineering trials. A further 10 trials use fitted R1 M1 member predictions as truth. Both are known-one-mode positive controls with hypothetical Gaussian member noise, not C20 false-positive calibration. Full truth, noise, observation, candidates and hashes are included. Real-data member search uses 12 starts; controls use 4 and cannot substitute for matched-budget inference.', ...
 '## Remaining checks and next decision', ...
 'Prioritize a named shared-width-release or center-curvature M1 comparison, and R1 time-block single-versus-double descriptions, before promoting two components to two simultaneous excitations. Treat q-profile change as a sensitivity, not an automatic lateral correction. Dark/elastic reference and correlated noise validation are still needed for statistical intervals or intrinsic linewidth.', ...
 sprintf('Tests: %d passed, %d failed (6 new v5, 10 v4 contracts, 7 legacy). No full-repository claim. Saved A1/member observations, candidates, curves and corrected areas independently recompute before packaging; the ZIP is then extracted for a second check.',sum(tests.Passed),sum(tests.Failed)), ...
 'Visual inspection covered actual member residual plots and A0/A1 diagnostics. Numerical fit quality, model adequacy, parameter identifiability and physical origin are separate statuses.', ...
 'Recompute the extracted packet without native NPY: add the bundled src tree and case_studies/bisb2026/scripts to MATLAB path, then result=c20_v5_verify(packet_folder).'}];
c20_v4_io('text',fullfile(out,'run_report.md'),strjoin(text,newline));
c20_v4_io('text',fullfile(out,'next_action.md'),'Do not rerun this pilot. Next named comparison: release local M1 shared width/linear-center assumption with explicit matched nuisance structure, then examine actual time-block single-mode evolution. No experimental CI or physical attribution until correlated-noise and response limitations are addressed.');
delivery=out;
if ~isempty(delivery_name), delivery=fullfile(out,delivery_name); assert(~isfolder(delivery)); mkdir(delivery); end
packet=fullfile(delivery,'review_packet'); assert(~isfolder(packet)); mkdir(packet);
for name={'audit','A0_A1','member_models','sequence_models','q_center_diagnostics','validation','tests','provenance'}
 copyfile(fullfile(out,name{1}),fullfile(packet,name{1}));
end
for name={'run_report.md','stage_status.json','config_resolved.json','parent_packet_reference.json','next_action.md'}, copyfile(fullfile(out,name{1}),packet); end
c20_v4_io('text',fullfile(packet,'README.md'),strjoin({'Read run_report.md first. Complete A1 and M1/M2 arrays/candidates, actual member and sequence inputs, q profiles, positive controls and source snapshots are included.', ...
 'Areas: audit/area_arrays.mat and area_scope_corrected.csv. Members: member_models/all_member_fits.mat and per-region member_fit.mat/derived_bin_predictions.mat. All individual predictions and residuals are preserved.', ...
 'Source and input hashes identify core and auxiliary stages. No native giant NPY or modified parent output is included.', ...
 'FILE_MANIFEST.csv provides all payload sizes and SHA256. Actual archive extraction/readback results are saved beside the outer ZIP.'},newline));
files=c20_v4_io('inventory',packet); writetable(files,fullfile(packet,'FILE_MANIFEST.csv'));
archive=fullfile(delivery,'review_packet.zip'); assert(~isfile(archive)); zip(archive,{'*'},packet);
decoded=fullfile(delivery,'packet_readback'); assert(~isfolder(decoded)); mkdir(decoded); unzip(archive,decoded);
list=readtable(fullfile(decoded,'FILE_MANIFEST.csv'),TextType='string');
for k=1:height(list), assert(strcmpi(c20_v4_io('hash',fullfile(decoded,list.path(k))),list.sha256(k))); end
verified=c20_v5_verify(decoded); c20_v4_io('json',fullfile(delivery,'packet_readback_result.json'),verified);
disp(['ARCHIVE=' archive]);
end
