function archive = c20_v4_package(out)
% Stage deliverables, hash, archive, independently extract and read back.
packet=fullfile(out,'review_packet'); assert(~isfolder(packet),'Packet exists; refusing overwrite'); mkdir(packet);
for name={'audit','590_PL2_10w','validation','tests','provenance'}
 copyfile(fullfile(out,name{1}),fullfile(packet,name{1}));
end
copyfile(fullfile(out,'stage_status.json'),packet);
copyfile(fullfile(out,'run_report.md'),packet);
copyfile(which('c20_v4_verify_packet'),fullfile(packet,'c20_v4_verify_packet.m'));
c20_v4_io('text',fullfile(packet,'README.md'),strjoin({ ...
 '# C20 v4 reproducible review packet', ...
 'Read run_report.md and stage_status.json before using any result.', ...
 '590_PL2_10w/fit_details.mat: reconstructed legacy 12 models, 18 components, all 288 optimized candidates.', ...
 'solver_background_comparison.mat: same-data independent starts and nonnegative-constant background comparisons, all fits and candidates.', ...
 'sequence_block_spectra.mat: original representative q-member spectra (E x sequence x member), actual six blocks, A0/A1 members, shifts and common support.', ...
 'centered_binned_spectra.mat: exact source members, raw member curves, sum/mean and nominal q edges for nine bins.', ...
 'audit/component_mappings.mat and candidate CSV: all parent optimizer-to-ordered mappings. No parent fits were rerun.', ...
 'validation/: hypothetical engineering simulations and descriptive profiles, not C20 statistical confidence.', ...
 'tests/: actual new and regression results. No claim of full repository coverage.', ...
 'FILE_MANIFEST.csv lists relative paths, sizes and SHA256 of payload files (not itself).', ...
 'No giant native NPY is included. Add provenance/source_snapshot/src recursively and call c20_v4_verify_packet on this extracted folder.', ...
 'The outer archive is independently extracted and every native curve/candidate objective and real block is recomputed before delivery.'},newline));
manifest=c20_v4_io('inventory',packet); writetable(manifest,fullfile(packet,'FILE_MANIFEST.csv'));
archive=fullfile(out,'review_packet.zip'); assert(~isfile(archive));
zip(archive,{'*'},packet);
decoded=fullfile(out,'packet_readback'); assert(~isfolder(decoded)); mkdir(decoded); unzip(archive,decoded);
got=readtable(fullfile(decoded,'FILE_MANIFEST.csv'),TextType='string');
for k=1:height(got), assert(strcmpi(c20_v4_io('hash',fullfile(decoded,got.path(k))),got.sha256(k)),'ZIP file hash mismatch'); end
result=c20_v4_verify_packet(decoded);
save(fullfile(out,'packet_readback_result.mat'),'result');
c20_v4_io('json',fullfile(out,'packet_readback_result.json'),rmfield(result,'fit_checks'));
writetable(result.fit_checks,fullfile(out,'packet_readback_fit_checks.csv'));
disp(['ARCHIVE=' archive]);
end
