function out = run_b1_lorentz_tracking_upper_stability(options)
%RUN_B1_LORENTZ_TRACKING_UPPER_STABILITY Stabilize B1 upper branch.
%
% This controller keeps the existing mandatory Lorentz double-peak,
% signed-q, no +q/-q averaging workflow. It adds upper-branch diagnostics,
% a narrower upper tracking window, and an optional overbroad-upper retry.

arguments
    options.targetScore (1,1) double = 300
    options.runExtraction (1,1) logical = true
    options.runOverlay (1,1) logical = true
    options.runSandboxFit (1,1) logical = true
    options.visualGateApproved (1,1) logical = false
end

script_dir = fileparts(mfilename('fullpath'));
project_root = bisb_find_project_root(script_dir);
addpath(script_dir);
startup_path = fullfile(project_root, 'startup.m');
if isfile(startup_path)
    run(startup_path);
end

summary_dir = fullfile(project_root, 'paper_results', ...
    'b1_lorentz_tracking_optimization_260510_upper_stability');
if ~isfolder(summary_dir)
    mkdir(summary_dir);
end

variants = local_variant_specs();
all_metrics = local_empty_metrics_table();
all_upper_diagnostics = table();
variant_outputs = local_empty_variant_output();

for vi = 1:numel(variants)
    variant = variants(vi);
    fprintf('\n=== B1 upper stability %s ===\n', variant.id);
    if options.runExtraction && variant.run_extraction
        local_run_variant(project_root, summary_dir, variant);
    end
    [metrics, upper_diag] = local_finalize_variant(project_root, ...
        summary_dir, variant);
    all_metrics = [all_metrics; metrics]; %#ok<AGROW>
    all_upper_diagnostics = [all_upper_diagnostics; upper_diag]; %#ok<AGROW>
    score = local_variant_score(metrics, variant.id);
    gate = local_gate_status(metrics, variant.id, options.targetScore);
    overlay = struct('png', "", 'pdf', "");
    if options.runOverlay
        overlay = run_b1_double_peak_waterfall_extraction_overlay( ...
            dateTag=variant.final_tag);
    end
    variant_outputs(end + 1) = local_variant_output(variant, score, ...
        gate, overlay); %#ok<AGROW>
end

metrics_path = fullfile(summary_dir, ...
    'b1_lorentz_tracking_upper_stability_metrics.csv');
writetable(all_metrics, metrics_path);
diagnostics_path = fullfile(summary_dir, ...
    'b1_lorentz_tracking_upper_stability_upper_jump_gamma_R2.csv');
writetable(all_upper_diagnostics, diagnostics_path);
variant_path = fullfile(summary_dir, ...
    'b1_lorentz_tracking_upper_stability_variants.csv');
writetable(local_variant_outputs_table(variant_outputs), variant_path);

best_output = local_choose_best_output(variant_outputs);
local_copy_variant_overlays(summary_dir, variant_outputs);
gate_passed = best_output.metric_gate_passed;
if strlength(best_output.overlay_png) > 0 && isfile(best_output.overlay_png)
    copyfile(best_output.overlay_png, fullfile(summary_dir, ...
        'b1_double_peak_lorentz_tracking_upper_stability_overlay_three_dataset_comparison.png'));
end
if strlength(best_output.overlay_pdf) > 0 && isfile(best_output.overlay_pdf)
    copyfile(best_output.overlay_pdf, fullfile(summary_dir, ...
        'b1_double_peak_lorentz_tracking_upper_stability_overlay_three_dataset_comparison.pdf'));
end

fit_outputs = struct();
if gate_passed && options.visualGateApproved && options.runSandboxFit
    local_write_candidate_marker(summary_dir, best_output, options.targetScore);
    fit_outputs = local_run_final_candidate_fit(project_root, ...
        best_output.final_tag);
elseif gate_passed
    local_write_visual_review_marker(summary_dir, best_output, ...
        options.targetScore);
else
    local_write_manual_anchor_template(project_root, summary_dir, best_output);
end

readme_path = fullfile(summary_dir, ...
    'README_lorentz_tracking_upper_stability.md');
local_write_readme(readme_path, all_metrics, variant_outputs, best_output, ...
    options.targetScore, options.visualGateApproved);
local_register_outputs(project_root, summary_dir, best_output, gate_passed && ...
    options.visualGateApproved);

out = struct();
out.summary_dir = summary_dir;
out.metrics_csv = metrics_path;
out.upper_diagnostics_csv = diagnostics_path;
out.variants_csv = variant_path;
out.readme = readme_path;
out.best = best_output;
out.best_score = best_output.score;
out.metric_gate_passed = gate_passed;
out.visual_gate_approved = options.visualGateApproved;
out.fit_outputs = fit_outputs;

fprintf('\nB1 upper stability complete.\n');
fprintf('  Summary: %s\n', summary_dir);
fprintf('  Best: %s (%s), score %.3g, metric gate %d, visual gate %d\n', ...
    best_output.id, best_output.final_tag, best_output.score, ...
    gate_passed, options.visualGateApproved);
end


function variants = local_variant_specs()
variants = repmat(local_empty_variant(), 1, 6);
variants(1) = local_make_variant('u1_window300_2100_propagated_seed', ...
    '260510_lorentz_tracking_upper_stability_u1_window300_2100_propagated_seed', ...
    '', 'propagated_double_peak', true, false, [300 2100], true);
variants(2) = local_make_variant('u2_upper_trend_window_refit', ...
    '260510_lorentz_tracking_upper_stability_u2_trendwindow', ...
    '260510_lorentz_tracking_upper_stability_u1_window300_2100_propagated_seed', ...
    'windowed_branch_tracking', true, false, [300 2100], true);
variants(3) = local_make_variant('u3_upper_quality_retry', ...
    '260510_lorentz_tracking_upper_stability_u3_qualityretry', ...
    '260510_lorentz_tracking_upper_stability_u2_trendwindow', ...
    'windowed_branch_tracking', true, true, [300 2100], true);
variants(4) = local_make_variant('u4_window300_2000_qualityretry', ...
    '260510_lorentz_tracking_upper_stability_u4_window300_2000_qualityretry', ...
    '260510_lorentz_tracking_upper_stability_u2_trendwindow', ...
    'windowed_branch_tracking', true, true, [300 2000], true);
variants(5) = local_make_variant('u5_window300_1800_qualityretry', ...
    '260510_lorentz_tracking_upper_stability_u5_window300_1800_qualityretry', ...
    '260510_lorentz_tracking_upper_stability_u2_trendwindow', ...
    'windowed_branch_tracking', true, true, [300 1800], true, 250);
variants(6) = local_make_variant('u6_window300_2100_repair180', ...
    '260510_lorentz_tracking_upper_stability_u6_window300_2100_repair180', ...
    '260510_lorentz_tracking_upper_stability_u2_trendwindow', ...
    'windowed_branch_tracking', true, false, [300 2100], true, 180);
end


function variant = local_empty_variant()
variant = struct('id', '', 'final_tag', '', 'reference_tag', '', ...
    'tracking_mode', 'windowed_branch_tracking', ...
    'run_extraction', false, 'upper_quality_retry', false, ...
    'b1_energy_window', [NaN NaN], 'candidate_for_recommendation', false, ...
    'large_jump_threshold_meV', 250);
end


function variant = local_make_variant(id, final_tag, reference_tag, ...
    tracking_mode, run_extraction, upper_quality_retry, b1_energy_window, ...
    candidate_for_recommendation, large_jump_threshold_meV)
if nargin < 9 || isempty(large_jump_threshold_meV)
    large_jump_threshold_meV = 250;
end
variant = local_empty_variant();
variant.id = id;
variant.final_tag = final_tag;
variant.reference_tag = reference_tag;
variant.tracking_mode = tracking_mode;
variant.run_extraction = run_extraction;
variant.upper_quality_retry = upper_quality_retry;
variant.b1_energy_window = b1_energy_window;
variant.candidate_for_recommendation = candidate_for_recommendation;
variant.large_jump_threshold_meV = large_jump_threshold_meV;
end


function local_run_variant(project_root, summary_dir, variant)
sessions = {'590', 'n0', '20w'};
for si = 1:numel(sessions)
    session_request = sessions{si};
    lower_ref = table();
    upper_ref = table();
    if strlength(string(variant.reference_tag)) > 0
        ref_dir = local_session_dir(project_root, session_request, ...
            variant.reference_tag);
        lower_ref = readtable(fullfile(ref_dir, ...
            'b1_double_peak_lower_points.csv'));
        upper_ref_raw = readtable(fullfile(ref_dir, ...
            'b1_double_peak_upper_points.csv'));
        upper_ref = local_robust_upper_reference(upper_ref_raw);
        ref_csv = fullfile(summary_dir, sprintf( ...
            '%s_%s_upper_robust_trend_reference.csv', ...
            variant.id, session_request));
        writetable(upper_ref, ref_csv);
    end
    local_call_extraction(session_request, variant, lower_ref, upper_ref);
end
end


function local_call_extraction(session_request, variant, lower_ref, upper_ref)
run_b1_double_peak_binning_analysis(session_request, ...
    runFits=false, ...
    outputDateTag=variant.final_tag, ...
    qRangeOverride_Ainv=[-0.15 0.15], ...
    b1EnergyWindowOverrideMeV=variant.b1_energy_window, ...
    peakModelOverride='lorentz', ...
    trackingMode=variant.tracking_mode, ...
    fallbackSplitCandidatesMeV=[120 160 220], ...
    maxTrackingShiftMeV=260, ...
    trackingWindowHalfWidthMeV=320, ...
    trackingWindowHighQHalfWidthMeV=420, ...
    trackingWindowHighQAbsAinv=0.09, ...
    trackingWindowInvalidFallback='independent_double_peak', ...
    upperTrackingWindowHalfWidthMeV=180, ...
    upperTrackingWindowHighQHalfWidthMeV=240, ...
    upperTrackingWindowHighQAbsAinv=0.09, ...
    upperQualityRetry=variant.upper_quality_retry, ...
    upperMaxGammaOverE=1.4, ...
    upperMaxGammaMeV=1600, ...
    upperRetryWindowHalfWidthMeV=120, ...
    upperRetryHighQHalfWidthMeV=180, ...
    upperRetryHighQAbsAinv=0.09, ...
    referenceLowerPoints=lower_ref, ...
    referenceUpperPoints=upper_ref, ...
    waterfallStartMeV=250, ...
    waterfallEndMeV=1600, ...
    waterfallNormMode='area', ...
    waterfallAreaNormWindowMeV=[50 3800], ...
    waterfallResidual=true, ...
    waterfallGain=2, ...
    fitDenoiseMethod='sgolay', ...
    fitDenoiseProfile='adaptive_absq', ...
    fitDenoiseLowWindow=11, ...
    fitDenoiseHighWindow=91, ...
    fitDenoiseQStartAinv=0.07, ...
    fitDenoiseQEndAinv=0.15, ...
    fitDenoiseOrder=3, ...
    highQForceBinAbsAinv=0.075, ...
    binSize=9, ...
    enableJumpRepair=true, ...
    largeJumpThresholdMeV=variant.large_jump_threshold_meV);
end


function ref = local_robust_upper_reference(points)
if isempty(points) || height(points) == 0
    ref = table();
    return
end
q = double(points.q_Ainv(:));
energy = double(points.energy_meV(:));
valid = isfinite(q) & isfinite(energy);
q = q(valid);
energy = energy(valid);
[q, order] = sort(q);
energy = energy(order);
[q_unique, ~, group] = unique(q);
energy_unique = splitapply(@median, energy, group);
if numel(energy_unique) >= 5
    energy_unique = smoothdata(energy_unique, 'movmedian', 3);
    span = min(7, numel(energy_unique));
    if mod(span, 2) == 0
        span = span - 1;
    end
    if span >= 3
        energy_unique = smoothdata(energy_unique, 'rlowess', span);
    end
elseif numel(energy_unique) >= 3
    energy_unique = smoothdata(energy_unique, 'movmedian', 3);
end
ref = table(q_unique(:), energy_unique(:), ...
    'VariableNames', {'q_Ainv', 'energy_meV'});
end


function [metrics, upper_diag] = local_finalize_variant(project_root, ...
    summary_dir, variant)
metrics = local_empty_metrics_table();
upper_diag = table();
sessions = {'590', 'n0', '20w'};
for si = 1:numel(sessions)
    session_dir = local_session_dir(project_root, sessions{si}, ...
        variant.final_tag);
    local_copy_variant_named_csv(session_dir, variant.id);
    [rows, diag_rows] = local_metrics_one_session(session_dir, variant);
    writetable(rows, fullfile(session_dir, sprintf( ...
        'b1_double_peak_lorentz_tracking_upper_stability_%s_tracking_metrics.csv', ...
        variant.id)));
    writetable(diag_rows, fullfile(session_dir, sprintf( ...
        'b1_double_peak_lorentz_tracking_upper_stability_%s_upper_jump_gamma_R2.csv', ...
        variant.id)));
    metrics = [metrics; rows]; %#ok<AGROW>
    upper_diag = [upper_diag; diag_rows]; %#ok<AGROW>
end
if ~isempty(upper_diag)
    writetable(upper_diag, fullfile(summary_dir, sprintf( ...
        'b1_double_peak_lorentz_tracking_upper_stability_%s_upper_jump_gamma_R2.csv', ...
        variant.id)));
end
end


function local_copy_variant_named_csv(session_dir, variant_id)
copies = { ...
    'b1_double_peak_combined_q_points.csv', 'combined_points.csv'; ...
    'b1_double_peak_lower_points.csv', 'lower_points.csv'; ...
    'b1_double_peak_upper_points.csv', 'upper_points.csv'; ...
    'b1_double_peak_fit_failures.csv', 'failures.csv'; ...
    'b1_double_peak_repair_log.csv', 'repair_log.csv'; ...
    'b1_double_peak_exclusion_points.csv', 'exclusion_points.csv'; ...
    'b1_double_peak_binning_map.csv', 'binning_map.csv'};
for i = 1:size(copies, 1)
    src = fullfile(session_dir, copies{i, 1});
    if isfile(src)
        dst = fullfile(session_dir, sprintf( ...
            'b1_double_peak_lorentz_tracking_upper_stability_%s_%s', ...
            variant_id, copies{i, 2}));
        copyfile(src, dst);
    end
end
end


function [metrics, upper_diag] = local_metrics_one_session(session_dir, variant)
lower = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_lower_points.csv'));
upper = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_upper_points.csv'));
failures = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_fit_failures.csv'));
repair_log = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_repair_log.csv'));
exclusions = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_exclusion_points.csv'));

session_key = local_session_key_from_dir(session_dir);
failure_count = height(failures);
repair_count = height(repair_log);
exclusion_count = max(height(exclusions), failure_count);
metrics = [ ...
    local_branch_metric_row(variant, session_key, 'lower', lower, ...
    failure_count, repair_count, exclusion_count); ...
    local_branch_metric_row(variant, session_key, 'upper', upper, ...
    failure_count, repair_count, exclusion_count)];
upper_diag = local_upper_diagnostics(variant, session_key, upper);
end


function row = local_branch_metric_row(variant, session_key, branch, points, ...
    failure_count, repair_count, exclusion_count)
n_points = height(points);
jump_count = 0;
edge_count = 0;
if n_points >= 1 && ismember('energy_meV', points.Properties.VariableNames)
    edge_count = sum(points.energy_meV < 650 | points.energy_meV > 1900, ...
        'omitnan');
end
if n_points >= 2 && all(ismember({'q_Ainv', 'energy_meV'}, ...
        points.Properties.VariableNames))
    [~, order] = sort(points.q_Ainv);
    energy = points.energy_meV(order);
    jump_count = sum(abs(diff(energy)) > 250, 'omitnan');
end
weight = 1;
if strcmp(session_key, 'no_PL2_20w_2film')
    weight = 2;
end
raw_score = 10 * jump_count + 3 * edge_count + 5 * failure_count;
weighted_score = weight * raw_score;
upper = local_empty_upper_metric_values();
if strcmp(branch, 'upper')
    upper = b1_double_peak_upper_stability_metrics(points, session_key);
end
row = table({variant.id}, {variant.final_tag}, ...
    variant.candidate_for_recommendation, ...
    variant.b1_energy_window(1), variant.b1_energy_window(2), ...
    {session_key}, {branch}, ...
    n_points, jump_count, edge_count, failure_count, repair_count, ...
    exclusion_count, weight, raw_score, weighted_score, ...
    upper.upper_medium_jump_threshold_meV(1), ...
    upper.upper_large_jump_threshold_meV(1), ...
    upper.upper_medium_jump_count(1), ...
    upper.upper_large_jump_count(1), ...
    upper.upper_max_abs_jump_meV(1), ...
    upper.upper_overbroad_count(1), ...
    upper.upper_low_r2_count(1), ...
    upper.upper_stability_score(1), ...
    'VariableNames', {'variant_id', 'date_tag', ...
    'candidate_for_recommendation', 'b1_energy_min_meV', ...
    'b1_energy_max_meV', 'session_key', 'branch', ...
    'n_points', 'large_jump_count', 'edge_count', ...
    'failure_count', 'repair_count', 'exclusion_count', ...
    'session_weight', 'raw_score', 'weighted_score', ...
    'upper_medium_jump_threshold_meV', ...
    'upper_large_jump_threshold_meV', 'upper_medium_jump_count', ...
    'upper_large_jump_count', 'upper_max_abs_jump_meV', ...
    'upper_overbroad_count', 'upper_low_r2_count', ...
    'upper_stability_score'});
end


function values = local_empty_upper_metric_values()
values = table({''}, 0, NaN, 180, 0, 0, NaN, 0, 1.4, 1600, 0, 0.50, ...
    NaN, NaN, 0, 'VariableNames', {'session_key', 'n_upper_points', ...
    'upper_medium_jump_threshold_meV', ...
    'upper_large_jump_threshold_meV', 'upper_medium_jump_count', ...
    'upper_large_jump_count', 'upper_max_abs_jump_meV', ...
    'upper_overbroad_count', 'upper_max_gamma_over_E', ...
    'upper_max_gamma_meV', 'upper_low_r2_count', ...
    'upper_low_r2_threshold', 'upper_median_gamma_over_E', ...
    'upper_median_R2', 'upper_stability_score'});
end


function diag_rows = local_upper_diagnostics(variant, session_key, upper)
if isempty(upper) || height(upper) == 0
    diag_rows = table();
    return
end
[~, order] = sort(double(upper.q_Ainv));
upper = upper(order, :);
n = height(upper);
delta = [NaN; abs(diff(double(upper.energy_meV)))];
threshold = b1_double_peak_upper_stability_metrics(upper, session_key). ...
    upper_medium_jump_threshold_meV(1);
gamma_over_E = double(upper.gamma_meV) ./ max(abs(double(upper.energy_meV)), eps);
is_medium_jump = delta > threshold;
is_large_jump = delta > 180;
is_overbroad = gamma_over_E > 1.4 | double(upper.gamma_meV) > 1600;
source_mode = local_text_column(upper, 'source_mode');
source_q_Ainv = local_text_column(upper, 'source_q_Ainv');
repair_source = local_text_column(upper, 'repair_source');
repair_detail = local_text_column(upper, 'repair_detail');
diag_rows = table(repmat({variant.id}, n, 1), ...
    repmat({variant.final_tag}, n, 1), ...
    repmat(variant.candidate_for_recommendation, n, 1), ...
    repmat(variant.b1_energy_window(1), n, 1), ...
    repmat(variant.b1_energy_window(2), n, 1), ...
    repmat({session_key}, n, 1), ...
    upper.q_Ainv, upper.q_abs_Ainv, upper.energy_meV, delta, ...
    upper.gamma_meV, gamma_over_E, upper.R2, is_medium_jump, ...
    is_large_jump, is_overbroad, source_mode, ...
    upper.source_q_count, source_q_Ainv, repair_source, ...
    repair_detail, ...
    'VariableNames', {'variant_id', 'date_tag', ...
    'candidate_for_recommendation', 'b1_energy_min_meV', ...
    'b1_energy_max_meV', 'session_key', 'q_Ainv', 'q_abs_Ainv', ...
    'energy_meV', ...
    'delta_from_previous_meV', 'gamma_meV', 'gamma_over_E', 'R2', ...
    'is_upper_medium_jump', 'is_upper_large_jump_180', ...
    'is_overbroad_upper_peak', 'source_mode', 'source_q_count', ...
    'source_q_Ainv', 'repair_source', 'repair_detail'});
end


function score = local_variant_score(metrics, variant_id)
rows = strcmp(metrics.variant_id, variant_id);
if ~any(rows)
    score = Inf;
else
    score = sum(metrics.weighted_score(rows), 'omitnan');
end
end


function gate = local_gate_status(metrics, variant_id, target_score)
rows = strcmp(metrics.variant_id, variant_id);
if ismember('candidate_for_recommendation', metrics.Properties.VariableNames) && ...
        any(rows) && ~any(metrics.candidate_for_recommendation(rows))
    rows(:) = false;
end
upper_rows = rows & strcmp(metrics.branch, 'upper');
score = local_variant_score(metrics, variant_id);
gate = struct('total_score_ok', score <= target_score, ...
    'upper_medium_ok', false, 'upper_large_ok', false, ...
    'metric_gate_passed', false);
if ~any(upper_rows)
    return
end
upper = metrics(upper_rows, :);
is20w = strcmp(upper.session_key, 'no_PL2_20w_2film');
other = ~is20w;
gate.upper_medium_ok = any(is20w & upper.upper_medium_jump_count <= 3) && ...
    all(upper.upper_medium_jump_count(other) <= 2);
gate.upper_large_ok = all(upper.upper_large_jump_count == 0);
gate.metric_gate_passed = gate.total_score_ok && ...
    gate.upper_medium_ok && gate.upper_large_ok;
end


function best = local_choose_best_output(outputs)
if isempty(outputs)
    best = struct('id', '', 'final_tag', '', 'score', Inf, ...
        'candidate_for_recommendation', false, ...
        'b1_energy_min_meV', NaN, 'b1_energy_max_meV', NaN, ...
        'metric_gate_passed', false, 'overlay_png', "", 'overlay_pdf', "");
    return
end
recommendable = [outputs.candidate_for_recommendation];
gate = [outputs.metric_gate_passed] & recommendable;
if any(gate)
    candidates = find(gate);
else
    candidates = find(recommendable);
    if isempty(candidates)
        candidates = 1:numel(outputs);
    end
end
selection = [outputs(candidates).score] + ...
    [outputs(candidates).upper_stability_score];
[~, idx] = min(selection);
best = outputs(candidates(idx));
end


function local_copy_variant_overlays(summary_dir, variant_outputs)
for i = 1:numel(variant_outputs)
    safe_id = regexprep(variant_outputs(i).id, '[^A-Za-z0-9_]+', '_');
    if strlength(variant_outputs(i).overlay_png) > 0 && ...
            isfile(variant_outputs(i).overlay_png)
        copyfile(variant_outputs(i).overlay_png, fullfile(summary_dir, ...
            sprintf(['b1_double_peak_lorentz_tracking_upper_', ...
            'stability_%s_overlay_three_dataset_comparison.png'], safe_id)));
    end
    if strlength(variant_outputs(i).overlay_pdf) > 0 && ...
            isfile(variant_outputs(i).overlay_pdf)
        copyfile(variant_outputs(i).overlay_pdf, fullfile(summary_dir, ...
            sprintf(['b1_double_peak_lorentz_tracking_upper_', ...
            'stability_%s_overlay_three_dataset_comparison.pdf'], safe_id)));
    end
end
end


function output = local_variant_output(variant, score, gate, overlay)
if strlength(string(overlay.png)) == 0
    project_root = bisb_find_project_root(fileparts(mfilename('fullpath')));
    overlay_dir = fullfile(project_root, 'paper_results', ...
        sprintf(['b1_double_peak_waterfall_extraction_overlay_three_', ...
        'dataset_comparison_%s'], variant.final_tag));
    png = fullfile(overlay_dir, ...
        'b1_double_peak_waterfall_extraction_overlay_three_dataset_comparison.png');
    pdf = fullfile(overlay_dir, ...
        'b1_double_peak_waterfall_extraction_overlay_three_dataset_comparison.pdf');
    if isfile(png)
        overlay.png = string(png);
    end
    if isfile(pdf)
        overlay.pdf = string(pdf);
    end
end
upper_score = NaN;
try
    project_root = bisb_find_project_root(fileparts(mfilename('fullpath')));
    metrics = table();
    sessions = {'590', 'n0', '20w'};
    for si = 1:numel(sessions)
        session_dir = local_session_dir(project_root, sessions{si}, ...
            variant.final_tag);
        upper = local_read_table_if_exists(fullfile(session_dir, ...
            'b1_double_peak_upper_points.csv'));
        m = b1_double_peak_upper_stability_metrics(upper, ...
            local_session_key_from_dir(session_dir));
        metrics = [metrics; m]; %#ok<AGROW>
    end
    upper_score = sum(metrics.upper_stability_score, 'omitnan');
catch
    upper_score = Inf;
end
output = struct('id', variant.id, 'final_tag', variant.final_tag, ...
    'candidate_for_recommendation', variant.candidate_for_recommendation, ...
    'b1_energy_min_meV', variant.b1_energy_window(1), ...
    'b1_energy_max_meV', variant.b1_energy_window(2), ...
    'score', score, 'upper_stability_score', upper_score, ...
    'metric_gate_passed', gate.metric_gate_passed, ...
    'overlay_png', string(overlay.png), 'overlay_pdf', string(overlay.pdf));
end


function tbl = local_variant_outputs_table(outputs)
if isempty(outputs)
    tbl = table();
    return
end
tbl = table({outputs.id}.', {outputs.final_tag}.', ...
    [outputs.candidate_for_recommendation].', ...
    [outputs.b1_energy_min_meV].', [outputs.b1_energy_max_meV].', ...
    [outputs.score].', ...
    [outputs.upper_stability_score].', [outputs.metric_gate_passed].', ...
    string({outputs.overlay_png}).', string({outputs.overlay_pdf}).', ...
    'VariableNames', {'variant_id', 'date_tag', ...
    'candidate_for_recommendation', 'b1_energy_min_meV', ...
    'b1_energy_max_meV', 'score', ...
    'upper_stability_score', 'metric_gate_passed', ...
    'overlay_png', 'overlay_pdf'});
end


function fit_outputs = local_run_final_candidate_fit(project_root, final_tag)
datasets = local_fit_datasets(project_root, final_tag);
fit_outputs = struct();
fit_outputs.lower_physical = run_b1_physical_fit_analysis( ...
    datasets=datasets, ...
    branchFileName='b1_double_peak_lower_points.csv', ...
    outputTag='b1_double_peak_lorentz_tracking_upper_stability_final_candidate_fit_lower', ...
    filePrefix='b1_double_peak_lorentz_upper_stability_lower');
fit_outputs.upper_physical = run_b1_physical_fit_analysis( ...
    datasets=datasets, ...
    branchFileName='b1_double_peak_upper_points.csv', ...
    outputTag='b1_double_peak_lorentz_tracking_upper_stability_final_candidate_fit_upper', ...
    filePrefix='b1_double_peak_lorentz_upper_stability_upper');
fit_outputs.lower_enhancements = run_b1_physical_fit_enhancements( ...
    datasets=datasets, ...
    branchFileName='b1_double_peak_lower_points.csv', ...
    outputTag='b1_double_peak_lorentz_tracking_upper_stability_final_candidate_fit_lower_enhancements', ...
    filePrefix='b1_double_peak_lorentz_upper_stability_lower');
fit_outputs.upper_enhancements = run_b1_physical_fit_enhancements( ...
    datasets=datasets, ...
    branchFileName='b1_double_peak_upper_points.csv', ...
    outputTag='b1_double_peak_lorentz_tracking_upper_stability_final_candidate_fit_upper_enhancements', ...
    filePrefix='b1_double_peak_lorentz_upper_stability_upper');
end


function datasets = local_fit_datasets(project_root, tag)
requests = {'590', 'n0', '20w'};
keys = {'590_PL2_10w', 'n0_PL2_10w_repeat', 'no_PL2_20w_2film'};
labels = {'590 10w defocus 1film', ...
    'n0 10w defocus repeat 1film', '20w defocus 2film'};
classes = {'1film', '1film', '2film'};
factors = [1, 1, 2];
colors = {[0.120, 0.470, 0.900], [0.160, 0.500, 0.220], ...
    [0.930, 0.280, 0.300]};
datasets = struct('session_key', {}, 'session_label', {}, ...
    'input_dir', {}, 'thickness_class', {}, 'thickness_factor', {}, ...
    'color', {}, 'marker', {});
for i = 1:numel(requests)
    datasets(end + 1) = struct( ... %#ok<AGROW>
        'session_key', keys{i}, ...
        'session_label', labels{i}, ...
        'input_dir', local_session_dir(project_root, requests{i}, tag), ...
        'thickness_class', classes{i}, ...
        'thickness_factor', factors(i), ...
        'color', colors{i}, ...
        'marker', 'o');
end
end


function local_write_candidate_marker(summary_dir, best_output, target_score)
path = fullfile(summary_dir, ...
    'FINAL_CANDIDATE_REACHED_UPPER_STABILITY_GATE.txt');
fid = fopen(path, 'w', 'n', 'UTF-8');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'Final candidate reached upper stability gate.\n');
fprintf(fid, 'variant=%s\n', best_output.id);
fprintf(fid, 'date_tag=%s\n', best_output.final_tag);
fprintf(fid, 'score=%.12g\n', best_output.score);
fprintf(fid, 'target_score=%.12g\n', target_score);
fprintf(fid, 'visual_gate_approved=1\n');
end


function local_write_visual_review_marker(summary_dir, best_output, target_score)
path = fullfile(summary_dir, ...
    'UPPER_STABILITY_METRIC_GATE_PASSED_VISUAL_REVIEW_REQUIRED.txt');
fid = fopen(path, 'w', 'n', 'UTF-8');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'Metric gate passed, but sandbox fit is waiting for visual review.\n');
fprintf(fid, 'variant=%s\n', best_output.id);
fprintf(fid, 'date_tag=%s\n', best_output.final_tag);
fprintf(fid, 'score=%.12g\n', best_output.score);
fprintf(fid, 'target_score=%.12g\n', target_score);
fprintf(fid, 'visual_gate_approved=0\n');
end


function local_write_manual_anchor_template(project_root, summary_dir, best_output)
sessions = {'590', 'n0', '20w'};
anchor = table('Size', [0 7], ...
    'VariableTypes', {'cell', 'double', 'cell', 'double', 'double', ...
    'cell', 'cell'}, ...
    'VariableNames', {'session_request', 'q_Ainv', 'branch_label', ...
    'manual_lower_meV', 'manual_upper_meV', 'reason', 'detail'});
for si = 1:numel(sessions)
    session_dir = local_session_dir(project_root, sessions{si}, ...
        best_output.final_tag);
    failures = local_read_table_if_exists(fullfile(session_dir, ...
        'b1_double_peak_fit_failures.csv'));
    if all(ismember({'q_Ainv', 'status', 'detail'}, ...
            failures.Properties.VariableNames))
        for i = 1:height(failures)
            anchor = [anchor; table(sessions(si), failures.q_Ainv(i), ...
                {'both'}, NaN, NaN, failures.status(i), failures.detail(i), ...
                'VariableNames', anchor.Properties.VariableNames)]; %#ok<AGROW>
        end
    end
    upper = local_read_table_if_exists(fullfile(session_dir, ...
        'b1_double_peak_upper_points.csv'));
    diag_rows = local_upper_diagnostics(local_make_variant(best_output.id, ...
        best_output.final_tag, best_output.final_tag, ...
        'windowed_branch_tracking', false, false, ...
        [best_output.b1_energy_min_meV best_output.b1_energy_max_meV], ...
        best_output.candidate_for_recommendation), ...
        local_session_key_from_dir(session_dir), upper);
    if ~isempty(diag_rows)
        issue = diag_rows.is_upper_medium_jump | ...
            diag_rows.is_upper_large_jump_180 | ...
            diag_rows.is_overbroad_upper_peak;
        for i = find(issue(:).')
            reason = 'upper_tracking_issue';
            if diag_rows.is_overbroad_upper_peak(i)
                reason = 'overbroad_upper_peak';
            elseif diag_rows.is_upper_large_jump_180(i)
                reason = 'upper_large_jump_180';
            elseif diag_rows.is_upper_medium_jump(i)
                reason = 'upper_medium_jump';
            end
            anchor = [anchor; table(sessions(si), diag_rows.q_Ainv(i), ...
                {'upper'}, NaN, NaN, {reason}, {''}, ...
                'VariableNames', anchor.Properties.VariableNames)]; %#ok<AGROW>
        end
    end
end
writetable(anchor, fullfile(summary_dir, ...
    'b1_double_peak_upper_manual_anchor_template.csv'));
end


function local_write_readme(path, metrics, variant_outputs, best_output, ...
    target_score, visual_gate_approved)
fid = fopen(path, 'w', 'n', 'UTF-8');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# B1 Lorentz tracking upper stability\n\n');
fprintf(fid, '- Model: mandatory Lorentz double peak.\n');
fprintf(fid, '- q rule: signed q only; no +q/-q averaging.\n');
fprintf(fid, ['- Old 500 meV lower-bound results are deprecated and are not ', ...
    'used as candidates or tracking references.\n']);
fprintf(fid, ['- U1 builds a fresh propagated Lorentz seed with the ', ...
    '300-2100 meV B1 window; later variants only reference U1/U2.\n']);
fprintf(fid, ['- B1 double-peak fit candidate energy windows: ', ...
    '300-2100, 300-2000, and 300-1800 meV.\n']);
fprintf(fid, '- Upper medium-jump thresholds: 20w >120 meV; 590/n0 >150 meV.\n');
fprintf(fid, '- Upper overbroad flags: gamma/E > 1.4 or gamma > 1600 meV.\n');
fprintf(fid, '- Fit gate: total score <= %.3g plus upper stability thresholds.\n', ...
    target_score);
fprintf(fid, '- Visual gate approved: `%d`.\n', visual_gate_approved);
fprintf(fid, '- Best variant: `%s`, tag `%s`, score %.3g, metric gate `%d`.\n\n', ...
    best_output.id, best_output.final_tag, best_output.score, ...
    best_output.metric_gate_passed);

fprintf(fid, '## Variants\n\n');
fprintf(fid, '| variant | tag | candidate | B1 window | score | upper stability | metric gate | overlay |\n');
fprintf(fid, '| --- | --- | --- | --- | ---: | ---: | --- | --- |\n');
for i = 1:numel(variant_outputs)
    fprintf(fid, '| %s | %s | %d | %.0f-%.0f | %.3g | %.3g | %d | %s |\n', ...
        variant_outputs(i).id, variant_outputs(i).final_tag, ...
        variant_outputs(i).candidate_for_recommendation, ...
        variant_outputs(i).b1_energy_min_meV, ...
        variant_outputs(i).b1_energy_max_meV, ...
        variant_outputs(i).score, ...
        variant_outputs(i).upper_stability_score, ...
        variant_outputs(i).metric_gate_passed, ...
        local_file_name(variant_outputs(i).overlay_png));
end

fprintf(fid, '\n## Metrics\n\n');
fprintf(fid, ['| variant | candidate | B1 window | session | branch | ', ...
    'points | jumps>250 | edge | ', ...
    'failures | upper medium | upper >180 | overbroad | weighted score |\n']);
fprintf(fid, '| --- | --- | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n');
for i = 1:height(metrics)
    fprintf(fid, '| %s | %d | %.0f-%.0f | %s | %s | %d | %d | %d | %d | %d | %d | %d | %.3g |\n', ...
        local_cell_text(metrics.variant_id, i), ...
        metrics.candidate_for_recommendation(i), ...
        metrics.b1_energy_min_meV(i), metrics.b1_energy_max_meV(i), ...
        local_cell_text(metrics.session_key, i), ...
        local_cell_text(metrics.branch, i), metrics.n_points(i), ...
        metrics.large_jump_count(i), metrics.edge_count(i), ...
        metrics.failure_count(i), metrics.upper_medium_jump_count(i), ...
        metrics.upper_large_jump_count(i), ...
        metrics.upper_overbroad_count(i), metrics.weighted_score(i));
end
end


function local_register_outputs(project_root, summary_dir, best_output, ...
    register_candidate)
results_root = fullfile(project_root, 'paper_results');
current_dir = fullfile(results_root, '00_CURRENT_B1_DOUBLE_PEAK_260509');
if ~isfolder(current_dir)
    mkdir(current_dir);
end
date_dir = fullfile(results_root, '00-by_date', '2026-05-10');
if ~isfolder(date_dir)
    mkdir(date_dir);
end
targets = {summary_dir};
names = {'39_lorentz_tracking_upper_stability_summary'};
if register_candidate
    sessions = {'590', 'n0', '20w'};
    for si = 1:numel(sessions)
        targets{end + 1} = local_session_dir(project_root, sessions{si}, ...
            best_output.final_tag); %#ok<AGROW>
        names{end + 1} = sprintf( ...
            '%02d_%s_lorentz_tracking_upper_stability_best_extraction', ...
            39 + si, sessions{si}); %#ok<AGROW>
    end
    fit_dirs = { ...
        'b1_double_peak_lorentz_tracking_upper_stability_final_candidate_fit_lower', ...
        'b1_double_peak_lorentz_tracking_upper_stability_final_candidate_fit_upper', ...
        'b1_double_peak_lorentz_tracking_upper_stability_final_candidate_fit_lower_enhancements', ...
        'b1_double_peak_lorentz_tracking_upper_stability_final_candidate_fit_upper_enhancements'};
    for i = 1:numel(fit_dirs)
        target = fullfile(results_root, fit_dirs{i});
        if isfolder(target)
            targets{end + 1} = target; %#ok<AGROW>
            names{end + 1} = sprintf( ...
                '%02d_lorentz_tracking_upper_stability_%s', ...
                42 + i, strrep(fit_dirs{i}, ...
                'b1_double_peak_lorentz_tracking_upper_stability_', '')); %#ok<AGROW>
        end
    end
end
for i = 1:numel(targets)
    local_create_junction_if_missing(fullfile(current_dir, names{i}), targets{i});
    local_create_junction_if_missing(fullfile(date_dir, local_file_name(targets{i})), ...
        targets{i});
    local_append_manifest(project_root, '2026-05-10', 'current_work_date', ...
        local_file_name(targets{i}), fullfile(date_dir, local_file_name(targets{i})), ...
        targets{i});
end
end


function local_create_junction_if_missing(link_path, target_path)
if isfolder(link_path) || isfile(link_path) || ~isfolder(target_path)
    return
end
[parent, ~] = fileparts(link_path);
if ~isfolder(parent)
    mkdir(parent);
end
cmd = sprintf('cmd /c mklink /J "%s" "%s"', link_path, target_path);
system(cmd);
end


function local_append_manifest(project_root, date_text, category, name, ...
    bydate_path, target_path)
manifest = fullfile(project_root, 'paper_results', '00-by_date', ...
    '_manifest.csv');
line = sprintf('"%s","%s","%s","%s","%s","%s"', date_text, category, ...
    name, char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')), ...
    bydate_path, target_path);
if isfile(manifest)
    src = fileread(manifest);
    if contains(src, target_path)
        return
    end
    fid = fopen(manifest, 'a', 'n', 'UTF-8');
else
    fid = fopen(manifest, 'w', 'n', 'UTF-8');
    fprintf(fid, '"date","category","name","timestamp","by_date_path","target_path"\n');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', line);
end


function tbl = local_read_table_if_exists(path)
if isfile(path)
    tbl = readtable(path);
else
    tbl = table();
end
end


function metrics = local_empty_metrics_table()
metrics = table('Size', [0 24], ...
    'VariableTypes', {'cell', 'cell', 'logical', 'double', 'double', ...
    'cell', 'cell', 'double', ...
    'double', 'double', 'double', 'double', 'double', 'double', ...
    'double', 'double', 'double', 'double', 'double', 'double', ...
    'double', 'double', 'double', 'double'}, ...
    'VariableNames', {'variant_id', 'date_tag', ...
    'candidate_for_recommendation', 'b1_energy_min_meV', ...
    'b1_energy_max_meV', 'session_key', 'branch', ...
    'n_points', 'large_jump_count', 'edge_count', ...
    'failure_count', 'repair_count', 'exclusion_count', ...
    'session_weight', 'raw_score', 'weighted_score', ...
    'upper_medium_jump_threshold_meV', ...
    'upper_large_jump_threshold_meV', 'upper_medium_jump_count', ...
    'upper_large_jump_count', 'upper_max_abs_jump_meV', ...
    'upper_overbroad_count', 'upper_low_r2_count', ...
    'upper_stability_score'});
end


function outputs = local_empty_variant_output()
outputs = struct('id', {}, 'final_tag', {}, 'score', {}, ...
    'candidate_for_recommendation', {}, 'b1_energy_min_meV', {}, ...
    'b1_energy_max_meV', {}, ...
    'upper_stability_score', {}, 'metric_gate_passed', {}, ...
    'overlay_png', {}, 'overlay_pdf', {});
end


function session_dir = local_session_dir(project_root, session_request, tag)
switch session_request
    case '590'
        folder = sprintf('590_gui_history_area_260506_b1_double_peak_binning_%s', tag);
    case 'n0'
        folder = sprintf('n0_PL2_10w_gui_history_area_260506_b1_double_peak_binning_%s', tag);
    case '20w'
        folder = sprintf(['no_PL2_20w_2film_gui_history_area_260506_', ...
            'highq_refined_b1_double_peak_binning_%s'], tag);
    otherwise
        error('run_b1_lorentz_tracking_upper_stability:UnknownSession', ...
            'Unknown session "%s".', session_request);
end
session_dir = fullfile(project_root, 'paper_results', folder);
end


function key = local_session_key_from_dir(session_dir)
[~, name] = fileparts(session_dir);
if startsWith(name, '590_')
    key = '590_PL2_10w';
elseif startsWith(name, 'n0_')
    key = 'n0_PL2_10w_repeat';
elseif startsWith(name, 'no_PL2_20w')
    key = 'no_PL2_20w_2film';
else
    key = name;
end
end


function text = local_cell_text(value, row)
if iscell(value)
    text = char(value{row});
elseif isstring(value)
    text = char(value(row));
else
    text = char(string(value(row)));
end
end


function values = local_text_column(tbl, name)
if ~ismember(name, tbl.Properties.VariableNames)
    values = repmat({''}, height(tbl), 1);
    return
end
raw = tbl.(name);
if iscell(raw)
    values = cellfun(@(x) char(string(x)), raw, 'UniformOutput', false);
elseif isstring(raw)
    values = cellstr(raw);
else
    values = cellstr(string(raw));
end
values = values(:);
end


function name = local_file_name(path_value)
[~, name, ext] = fileparts(char(string(path_value)));
name = [name ext];
end
