function out = run_b1_lorentz_tracking_ridge_guided_optimization(options)
%RUN_B1_LORENTZ_TRACKING_RIDGE_GUIDED_OPTIMIZATION Ridge-guided B1 tracking.
%
% This controller keeps the clean 300 meV lower B1 window, mandatory
% Lorentz double peaks, signed-q traces, no +q/-q averaging, no single-peak
% fallback, and no physical fit. The ridge is used only to seed candidates.

arguments
    options.targetScore (1,1) double = 300
    options.runExtraction (1,1) logical = true
    options.runOverlay (1,1) logical = true
    options.manualAnchorPolicy {mustBeTextScalar} = "template_only"
end

script_dir = fileparts(mfilename('fullpath'));
project_root = bisb_find_project_root(script_dir);
addpath(script_dir);
startup_path = fullfile(project_root, 'startup.m');
if isfile(startup_path)
    run(startup_path);
end

if ~strcmp(char(string(options.manualAnchorPolicy)), 'template_only')
    error('run_b1_lorentz_tracking_ridge_guided_optimization:ManualAnchors', ...
        'manualAnchorPolicy must be template_only for this automatic run.');
end

summary_dir = fullfile(project_root, 'paper_results', ...
    'b1_lorentz_tracking_optimization_260510_ridge_guided');
if ~isfolder(summary_dir)
    mkdir(summary_dir);
end

variants = local_variant_specs();
all_metrics = local_empty_metrics_table();
all_upper_diagnostics = table();
variant_outputs = local_empty_variant_output();

for vi = 1:numel(variants)
    variant = variants(vi);
    fprintf('\n=== B1 ridge-guided %s ===\n', variant.id);
    if options.runExtraction
        local_run_variant(variant);
    end
    [metrics, upper_diag] = local_finalize_variant(project_root, ...
        summary_dir, variant);
    all_metrics = [all_metrics; metrics]; %#ok<AGROW>
    all_upper_diagnostics = [all_upper_diagnostics; upper_diag]; %#ok<AGROW>
    score = local_variant_score(metrics, variant.id);
    gate = score <= options.targetScore && ...
        variant.candidate_for_recommendation;
    overlay = struct('png', "", 'pdf', "");
    if options.runOverlay
        overlay = run_b1_double_peak_waterfall_extraction_overlay( ...
            dateTag=variant.final_tag);
    end
    variant_outputs(end + 1) = local_variant_output(variant, score, ...
        gate, overlay); %#ok<AGROW>
end

metrics_path = fullfile(summary_dir, ...
    'b1_lorentz_tracking_ridge_guided_metrics.csv');
writetable(all_metrics, metrics_path);
upper_diag_path = fullfile(summary_dir, ...
    'b1_lorentz_tracking_ridge_guided_upper_jump_gamma_R2.csv');
writetable(all_upper_diagnostics, upper_diag_path);
variant_path = fullfile(summary_dir, ...
    'b1_lorentz_tracking_ridge_guided_variants.csv');
writetable(local_variant_outputs_table(variant_outputs), variant_path);

best = local_choose_best_output(variant_outputs);
local_copy_variant_overlays(summary_dir, variant_outputs);
if strlength(best.overlay_png) > 0 && isfile(best.overlay_png)
    copyfile(best.overlay_png, fullfile(summary_dir, ...
        'b1_double_peak_lorentz_tracking_overlay_three_dataset_comparison.png'));
end
if strlength(best.overlay_pdf) > 0 && isfile(best.overlay_pdf)
    copyfile(best.overlay_pdf, fullfile(summary_dir, ...
        'b1_double_peak_lorentz_tracking_overlay_three_dataset_comparison.pdf'));
end

gate_passed = best.score <= options.targetScore;
if gate_passed
    local_write_final_candidate_marker(summary_dir, best, options.targetScore);
else
    local_write_manual_anchor_template(project_root, summary_dir, best);
    local_write_problem_points_overlay(summary_dir, best);
end

readme_path = fullfile(summary_dir, ...
    'README_lorentz_tracking_ridge_guided_optimization.md');
local_write_readme(readme_path, all_metrics, variant_outputs, best, ...
    options.targetScore, gate_passed);
local_register_outputs(project_root, summary_dir, best);
local_update_results_index(project_root, summary_dir, best, gate_passed);

out = struct();
out.summary_dir = summary_dir;
out.metrics_csv = metrics_path;
out.upper_diagnostics_csv = upper_diag_path;
out.variants_csv = variant_path;
out.readme = readme_path;
out.best = best;
out.best_score = best.score;
out.metric_gate_passed = gate_passed;

fprintf('\nB1 ridge-guided optimization complete.\n');
fprintf('  Summary: %s\n', summary_dir);
fprintf('  Best: %s (%s), score %.3g, gate %d\n', ...
    best.id, best.final_tag, best.score, gate_passed);
end


function variants = local_variant_specs()
variants = repmat(local_empty_variant(), 1, 6);
variants(1) = local_make_variant('v10a_300_2100_ridge_seed', ...
    '260510_lorentz_tracking_ridge_guided_v10a_300_2100_ridge_seed', ...
    [300 2100], 9, 91, 9, 91, false, false);
variants(2) = local_make_variant('v10b_300_2100_candidate_path', ...
    '260510_lorentz_tracking_ridge_guided_v10b_300_2100_candidate_path', ...
    [300 2100], 9, 91, 9, 91, false, true);
variants(3) = local_make_variant('v10c_300_2100_qualityretry', ...
    '260510_lorentz_tracking_ridge_guided_v10c_300_2100_qualityretry', ...
    [300 2100], 9, 91, 9, 91, true, true);
variants(4) = local_make_variant('v11a_20w_bin11_sg111', ...
    '260510_lorentz_tracking_ridge_guided_v11a_20w_bin11_sg111', ...
    [300 2100], 9, 91, 11, 111, true, true);
variants(5) = local_make_variant('v11b_20w_bin11_sg131', ...
    '260510_lorentz_tracking_ridge_guided_v11b_20w_bin11_sg131', ...
    [300 2100], 9, 91, 11, 131, true, true);
variants(6) = local_make_variant('v11c_300_1800_20w_bin11_sg111', ...
    '260510_lorentz_tracking_ridge_guided_v11c_300_1800_20w_bin11_sg111', ...
    [300 1800], 9, 91, 11, 111, true, true);
end


function variant = local_empty_variant()
variant = struct('id', '', 'final_tag', '', 'b1_energy_window', ...
    [300 2100], 'bin_default', 9, 'sg_default', 91, ...
    'bin_20w', 9, 'sg_20w', 91, 'upper_quality_retry', false, ...
    'candidate_for_recommendation', true);
end


function variant = local_make_variant(id, tag, b1_window, bin_default, ...
    sg_default, bin_20w, sg_20w, upper_quality_retry, candidate)
variant = local_empty_variant();
variant.id = id;
variant.final_tag = tag;
variant.b1_energy_window = b1_window;
variant.bin_default = bin_default;
variant.sg_default = sg_default;
variant.bin_20w = bin_20w;
variant.sg_20w = sg_20w;
variant.upper_quality_retry = upper_quality_retry;
variant.candidate_for_recommendation = candidate;
end


function local_run_variant(variant)
sessions = {'590', 'n0', '20w'};
for si = 1:numel(sessions)
    session_request = sessions{si};
    [bin_size, sg_high] = local_session_parameters(session_request, variant);
    run_b1_double_peak_binning_analysis(session_request, ...
        runFits=false, ...
        outputDateTag=variant.final_tag, ...
        qRangeOverride_Ainv=[-0.15 0.15], ...
        b1EnergyWindowOverrideMeV=variant.b1_energy_window, ...
        peakModelOverride='lorentz', ...
        trackingMode='ridge_guided_candidate_path', ...
        fallbackSplitCandidatesMeV=[120 160 220], ...
        maxTrackingShiftMeV=260, ...
        trackingWindowHalfWidthMeV=320, ...
        trackingWindowHighQHalfWidthMeV=420, ...
        trackingWindowHighQAbsAinv=0.09, ...
        trackingWindowInvalidFallback='independent_double_peak', ...
        upperQualityRetry=variant.upper_quality_retry, ...
        upperMaxGammaOverE=1.4, ...
        upperMaxGammaMeV=1600, ...
        upperRetryWindowHalfWidthMeV=120, ...
        upperRetryHighQHalfWidthMeV=180, ...
        upperRetryHighQAbsAinv=0.09, ...
        ridgeSmoothWindow=11, ...
        candidatePathUpperMediumJumpThresholdMeV=local_upper_threshold(session_request), ...
        candidatePathLargeJumpThresholdMeV=250, ...
        candidatePathEdgeEnergyMeV=[650 1900], ...
        waterfallStartMeV=250, ...
        waterfallEndMeV=1600, ...
        waterfallNormMode='area', ...
        waterfallAreaNormWindowMeV=[50 3800], ...
        waterfallResidual=true, ...
        waterfallGain=2, ...
        fitDenoiseMethod='sgolay', ...
        fitDenoiseProfile='adaptive_absq', ...
        fitDenoiseLowWindow=11, ...
        fitDenoiseHighWindow=sg_high, ...
        fitDenoiseQStartAinv=0.07, ...
        fitDenoiseQEndAinv=0.15, ...
        fitDenoiseOrder=3, ...
        highQForceBinAbsAinv=0.075, ...
        lowQNoBinAbsAinv=0.05, ... % low_q_no_bin_abs_Ainv=0.05
        binSize=bin_size, ...
        enableJumpRepair=false);
end
end


function [bin_size, sg_high] = local_session_parameters(session_request, variant)
if strcmp(session_request, '20w')
    bin_size = variant.bin_20w;
    sg_high = variant.sg_20w;
else
    bin_size = variant.bin_default;
    sg_high = variant.sg_default;
end
end


function threshold = local_upper_threshold(session_request)
if strcmp(session_request, '20w')
    threshold = 120;
else
    threshold = 150;
end
end


function [metrics, upper_diag] = local_finalize_variant(project_root, ...
    summary_dir, variant)
metrics = local_empty_metrics_table();
upper_diag = table();
sessions = {'590', 'n0', '20w'};
for si = 1:numel(sessions)
    session_dir = local_session_dir(project_root, sessions{si}, ...
        variant.final_tag);
    if ~isfolder(session_dir)
        mkdir(session_dir);
    end
    local_copy_variant_named_csv(session_dir, variant.id);
    [rows, diag_rows] = local_metrics_one_session(session_dir, variant);
    writetable(rows, fullfile(session_dir, sprintf( ...
        'b1_double_peak_lorentz_tracking_ridge_guided_%s_tracking_metrics.csv', ...
        variant.id)));
    writetable(diag_rows, fullfile(session_dir, sprintf( ...
        'b1_double_peak_lorentz_tracking_ridge_guided_%s_upper_jump_gamma_R2.csv', ...
        variant.id)));
    metrics = [metrics; rows]; %#ok<AGROW>
    upper_diag = [upper_diag; diag_rows]; %#ok<AGROW>
end
if ~isempty(upper_diag)
    writetable(upper_diag, fullfile(summary_dir, sprintf( ...
        'b1_double_peak_lorentz_tracking_ridge_guided_%s_upper_jump_gamma_R2.csv', ...
        variant.id)));
end
end


function local_copy_variant_named_csv(session_dir, variant_id)
copies = { ...
    'b1_double_peak_combined_q_points.csv', 'combined_points.csv'; ...
    'b1_double_peak_lower_points.csv', 'lower_points.csv'; ...
    'b1_double_peak_upper_points.csv', 'upper_points.csv'; ...
    'b1_double_peak_fit_failures.csv', 'failures.csv'; ...
    'b1_double_peak_repair_log.csv', 'repair_log.csv'; ...
    'b1_double_peak_exclusion_points.csv', 'exclusion_points.csv'; ...
    'b1_double_peak_binning_map.csv', 'binning_map.csv'; ...
    'b1_double_peak_lorentz_candidate_points.csv', 'candidate_points.csv'; ...
    'b1_double_peak_candidate_path_selection.csv', 'path_selection.csv'};
for i = 1:size(copies, 1)
    src = fullfile(session_dir, copies{i, 1});
    if isfile(src)
        dst = fullfile(session_dir, sprintf( ...
            'b1_double_peak_lorentz_tracking_ridge_guided_%s_%s', ...
            variant_id, copies{i, 2}));
        copyfile(src, dst);
    end
end
end


function [metrics, upper_diag] = local_metrics_one_session(session_dir, variant)
lower = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_lower_points.csv'));
upper = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_upper_points.csv'));
failures = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_fit_failures.csv'));
repair_log = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_repair_log.csv'));
exclusions = local_read_table_if_exists(fullfile(session_dir, ...
    'b1_double_peak_exclusion_points.csv'));

session_key = local_session_key_from_dir(session_dir);
failure_count = height(failures);
repair_count = height(repair_log);
exclusion_count = max(height(exclusions), failure_count);
metrics = [ ...
    local_branch_metric_row(variant, session_key, 'lower', lower, ...
    failure_count, repair_count, exclusion_count); ...
    local_branch_metric_row(variant, session_key, 'upper', upper, ...
    failure_count, repair_count, exclusion_count)];
upper_diag = local_upper_diagnostics(variant, session_key, upper);
end


function row = local_branch_metric_row(variant, session_key, branch, ...
    points, failure_count, repair_count, exclusion_count)
n_points = height(points);
jump_count = 0;
edge_count = 0;
if n_points >= 1 && ismember('energy_meV', points.Properties.VariableNames)
    edge_count = sum(points.energy_meV < 650 | points.energy_meV > 1900, ...
        'omitnan');
end
if n_points >= 2 && all(ismember({'q_Ainv', 'energy_meV'}, ...
        points.Properties.VariableNames))
    [~, order] = sort(points.q_Ainv);
    energy = points.energy_meV(order);
    jump_count = sum(abs(diff(energy)) > 250, 'omitnan');
end
weight = 1;
if strcmp(session_key, 'no_PL2_20w_2film')
    weight = 2;
end
raw_score = 10 * jump_count + 3 * edge_count + 5 * failure_count;
weighted_score = weight * raw_score;
upper = local_empty_upper_metric_values();
if strcmp(branch, 'upper')
    upper = b1_double_peak_upper_stability_metrics(points, session_key);
end
row = table({variant.id}, {variant.final_tag}, ...
    variant.candidate_for_recommendation, ...
    variant.b1_energy_window(1), variant.b1_energy_window(2), ...
    {session_key}, {branch}, ...
    n_points, jump_count, edge_count, failure_count, repair_count, ...
    exclusion_count, weight, raw_score, weighted_score, ...
    upper.upper_medium_jump_threshold_meV(1), ...
    upper.upper_large_jump_threshold_meV(1), ...
    upper.upper_medium_jump_count(1), ...
    upper.upper_large_jump_count(1), ...
    upper.upper_max_abs_jump_meV(1), ...
    upper.upper_overbroad_count(1), ...
    upper.upper_low_r2_count(1), ...
    upper.upper_stability_score(1), ...
    'VariableNames', {'variant_id', 'date_tag', ...
    'candidate_for_recommendation', 'b1_energy_min_meV', ...
    'b1_energy_max_meV', 'session_key', 'branch', ...
    'n_points', 'large_jump_count', 'edge_count', ...
    'failure_count', 'repair_count', 'exclusion_count', ...
    'session_weight', 'raw_score', 'weighted_score', ...
    'upper_medium_jump_threshold_meV', ...
    'upper_large_jump_threshold_meV', 'upper_medium_jump_count', ...
    'upper_large_jump_count', 'upper_max_abs_jump_meV', ...
    'upper_overbroad_count', 'upper_low_r2_count', ...
    'upper_stability_score'});
end


function values = local_empty_upper_metric_values()
values = table({''}, 0, NaN, 180, 0, 0, NaN, 0, 1.4, 1600, 0, 0.50, ...
    NaN, NaN, 0, 'VariableNames', {'session_key', 'n_upper_points', ...
    'upper_medium_jump_threshold_meV', ...
    'upper_large_jump_threshold_meV', 'upper_medium_jump_count', ...
    'upper_large_jump_count', 'upper_max_abs_jump_meV', ...
    'upper_overbroad_count', 'upper_max_gamma_over_E', ...
    'upper_max_gamma_meV', 'upper_low_r2_count', ...
    'upper_low_r2_threshold', 'upper_median_gamma_over_E', ...
    'upper_median_R2', 'upper_stability_score'});
end


function diag_rows = local_upper_diagnostics(variant, session_key, upper)
if isempty(upper) || height(upper) == 0
    diag_rows = table();
    return
end
[~, order] = sort(double(upper.q_Ainv));
upper = upper(order, :);
n = height(upper);
delta = [NaN; abs(diff(double(upper.energy_meV)))];
threshold = b1_double_peak_upper_stability_metrics(upper, session_key). ...
    upper_medium_jump_threshold_meV(1);
gamma_over_E = double(upper.gamma_meV) ./ max(abs(double(upper.energy_meV)), eps);
is_medium_jump = delta > threshold;
is_large_jump = delta > 180;
is_overbroad = gamma_over_E > 1.4 | double(upper.gamma_meV) > 1600;
source_mode = local_text_column(upper, 'source_mode');
source_q_Ainv = local_text_column(upper, 'source_q_Ainv');
repair_source = local_text_column(upper, 'repair_source');
repair_detail = local_text_column(upper, 'repair_detail');
diag_rows = table(repmat({variant.id}, n, 1), ...
    repmat({variant.final_tag}, n, 1), ...
    repmat(variant.candidate_for_recommendation, n, 1), ...
    repmat(variant.b1_energy_window(1), n, 1), ...
    repmat(variant.b1_energy_window(2), n, 1), ...
    repmat({session_key}, n, 1), ...
    upper.q_Ainv, upper.q_abs_Ainv, upper.energy_meV, delta, ...
    upper.gamma_meV, gamma_over_E, upper.R2, is_medium_jump, ...
    is_large_jump, is_overbroad, source_mode, ...
    upper.source_q_count, source_q_Ainv, repair_source, repair_detail, ...
    'VariableNames', {'variant_id', 'date_tag', ...
    'candidate_for_recommendation', 'b1_energy_min_meV', ...
    'b1_energy_max_meV', 'session_key', 'q_Ainv', 'q_abs_Ainv', ...
    'energy_meV', 'delta_from_previous_meV', 'gamma_meV', ...
    'gamma_over_E', 'R2', 'is_upper_medium_jump', ...
    'is_upper_large_jump_180', 'is_overbroad_upper_peak', ...
    'source_mode', 'source_q_count', 'source_q_Ainv', ...
    'repair_source', 'repair_detail'});
end


function score = local_variant_score(metrics, variant_id)
rows = strcmp(metrics.variant_id, variant_id);
if ~any(rows)
    score = Inf;
else
    score = sum(metrics.weighted_score(rows), 'omitnan');
end
end


function best = local_choose_best_output(outputs)
if isempty(outputs)
    best = struct('id', '', 'final_tag', '', 'score', Inf, ...
        'candidate_for_recommendation', false, ...
        'b1_energy_min_meV', NaN, 'b1_energy_max_meV', NaN, ...
        'metric_gate_passed', false, 'overlay_png', "", 'overlay_pdf', "");
    return
end
recommendable = [outputs.candidate_for_recommendation];
gate = [outputs.metric_gate_passed] & recommendable;
if any(gate)
    candidates = find(gate);
else
    candidates = find(recommendable);
    if isempty(candidates)
        candidates = 1:numel(outputs);
    end
end
selection = [outputs(candidates).score] + ...
    [outputs(candidates).upper_stability_score];
[~, idx] = min(selection);
best = outputs(candidates(idx));
end


function local_copy_variant_overlays(summary_dir, variant_outputs)
for i = 1:numel(variant_outputs)
    safe_id = regexprep(variant_outputs(i).id, '[^A-Za-z0-9_]+', '_');
    if strlength(variant_outputs(i).overlay_png) > 0 && ...
            isfile(variant_outputs(i).overlay_png)
        copyfile(variant_outputs(i).overlay_png, fullfile(summary_dir, ...
            sprintf(['b1_double_peak_lorentz_tracking_ridge_guided_', ...
            '%s_overlay_three_dataset_comparison.png'], safe_id)));
    end
    if strlength(variant_outputs(i).overlay_pdf) > 0 && ...
            isfile(variant_outputs(i).overlay_pdf)
        copyfile(variant_outputs(i).overlay_pdf, fullfile(summary_dir, ...
            sprintf(['b1_double_peak_lorentz_tracking_ridge_guided_', ...
            '%s_overlay_three_dataset_comparison.pdf'], safe_id)));
    end
end
end


function output = local_variant_output(variant, score, gate, overlay)
upper_score = NaN;
try
    project_root = bisb_find_project_root(fileparts(mfilename('fullpath')));
    metrics = table();
    sessions = {'590', 'n0', '20w'};
    for si = 1:numel(sessions)
        session_dir = local_session_dir(project_root, sessions{si}, ...
            variant.final_tag);
        upper = local_read_table_if_exists(fullfile(session_dir, ...
            'b1_double_peak_upper_points.csv'));
        metrics = [metrics; b1_double_peak_upper_stability_metrics( ...
            upper, local_session_key_from_dir(session_dir))]; %#ok<AGROW>
    end
    upper_score = sum(metrics.upper_stability_score, 'omitnan');
catch
    upper_score = Inf;
end
output = struct('id', variant.id, 'final_tag', variant.final_tag, ...
    'candidate_for_recommendation', variant.candidate_for_recommendation, ...
    'b1_energy_min_meV', variant.b1_energy_window(1), ...
    'b1_energy_max_meV', variant.b1_energy_window(2), ...
    'score', score, 'upper_stability_score', upper_score, ...
    'metric_gate_passed', gate, 'overlay_png', string(overlay.png), ...
    'overlay_pdf', string(overlay.pdf));
end


function tbl = local_variant_outputs_table(outputs)
if isempty(outputs)
    tbl = table();
    return
end
tbl = table({outputs.id}.', {outputs.final_tag}.', ...
    [outputs.candidate_for_recommendation].', ...
    [outputs.b1_energy_min_meV].', [outputs.b1_energy_max_meV].', ...
    [outputs.score].', [outputs.upper_stability_score].', ...
    [outputs.metric_gate_passed].', string({outputs.overlay_png}).', ...
    string({outputs.overlay_pdf}).', ...
    'VariableNames', {'variant_id', 'date_tag', ...
    'candidate_for_recommendation', 'b1_energy_min_meV', ...
    'b1_energy_max_meV', 'score', 'upper_stability_score', ...
    'metric_gate_passed', 'overlay_png', 'overlay_pdf'});
end


function local_write_final_candidate_marker(summary_dir, best, target_score)
path = fullfile(summary_dir, ...
    'RIDGE_GUIDED_FINAL_CANDIDATE_METRIC_GATE_PASSED_NO_FIT.txt');
fid = fopen(path, 'w', 'n', 'UTF-8');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'Metric gate passed. No physical fit was run in this round.\n');
fprintf(fid, 'variant=%s\n', best.id);
fprintf(fid, 'date_tag=%s\n', best.final_tag);
fprintf(fid, 'score=%.12g\n', best.score);
fprintf(fid, 'target_score=%.12g\n', target_score);
end


function local_write_manual_anchor_template(project_root, summary_dir, best)
sessions = {'590', 'n0', '20w'};
anchor = table('Size', [0 9], ...
    'VariableTypes', {'cell', 'double', 'cell', 'double', 'double', ...
    'double', 'double', 'cell', 'cell'}, ...
    'VariableNames', {'session_request', 'q_Ainv', 'branch_label', ...
    'manual_lower_min_meV', 'manual_lower_max_meV', ...
    'manual_upper_min_meV', 'manual_upper_max_meV', 'reason', 'detail'});
for si = 1:numel(sessions)
    session_dir = local_session_dir(project_root, sessions{si}, best.final_tag);
    failures = local_read_table_if_exists(fullfile(session_dir, ...
        'b1_double_peak_fit_failures.csv'));
    if all(ismember({'q_Ainv', 'status', 'detail'}, ...
            failures.Properties.VariableNames))
        for i = 1:height(failures)
            anchor = [anchor; table(sessions(si), failures.q_Ainv(i), ...
                {'both'}, NaN, NaN, NaN, NaN, failures.status(i), ...
                failures.detail(i), ...
                'VariableNames', anchor.Properties.VariableNames)]; %#ok<AGROW>
        end
    end
    upper = local_read_table_if_exists(fullfile(session_dir, ...
        'b1_double_peak_upper_points.csv'));
    diag_rows = local_upper_diagnostics(local_empty_variant(), ...
        local_session_key_from_dir(session_dir), upper);
    if ~isempty(diag_rows)
        issue = diag_rows.is_upper_medium_jump | ...
            diag_rows.is_upper_large_jump_180 | ...
            diag_rows.is_overbroad_upper_peak;
        for i = find(issue(:).')
            reason = 'upper_tracking_issue';
            if diag_rows.is_overbroad_upper_peak(i)
                reason = 'overbroad_upper_peak';
            elseif diag_rows.is_upper_large_jump_180(i)
                reason = 'upper_large_jump_180';
            elseif diag_rows.is_upper_medium_jump(i)
                reason = 'upper_medium_jump';
            end
            anchor = [anchor; table(sessions(si), diag_rows.q_Ainv(i), ...
                {'upper'}, NaN, NaN, NaN, NaN, {reason}, {''}, ...
                'VariableNames', anchor.Properties.VariableNames)]; %#ok<AGROW>
        end
    end
end
writetable(anchor, fullfile(summary_dir, ...
    'b1_double_peak_manual_anchor_template_ridge_guided.csv'));
end


function local_write_problem_points_overlay(summary_dir, best)
if strlength(best.overlay_png) > 0 && isfile(best.overlay_png)
    copyfile(best.overlay_png, fullfile(summary_dir, ...
        'b1_double_peak_problem_points_overlay.png'));
end
if strlength(best.overlay_pdf) > 0 && isfile(best.overlay_pdf)
    copyfile(best.overlay_pdf, fullfile(summary_dir, ...
        'b1_double_peak_problem_points_overlay.pdf'));
end
end


function local_write_readme(path, metrics, outputs, best, target_score, gate)
fid = fopen(path, 'w', 'n', 'UTF-8');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# B1 Lorentz ridge-guided tracking optimization\n\n');
fprintf(fid, '- Model: mandatory Lorentz double peak; no single-peak fallback.\n');
fprintf(fid, '- q rule: signed q only; no +q/-q averaging.\n');
fprintf(fid, '- B1 fit windows tested: 300-2100 and 300-1800 meV.\n');
fprintf(fid, '- Low-q protection: |q| <= 0.05 A^-1 is not force-binned.\n');
fprintf(fid, '- Ridge positions seed candidates only; final points come from Lorentz fits.\n');
fprintf(fid, '- Candidate path outputs: b1_double_peak_lorentz_candidate_points.csv and b1_double_peak_candidate_path_selection.csv.\n');
fprintf(fid, '- Physical fit status: not run in this round.\n');
fprintf(fid, '- Target score: %.3g. Best: `%s`, tag `%s`, score %.3g, gate `%d`.\n\n', ...
    target_score, best.id, best.final_tag, best.score, gate);

if ~gate
    fprintf(fid, 'Gate result: not entering fit; use the manual anchor template if automatic tracking remains unsatisfactory.\n\n');
else
    fprintf(fid, 'Gate result: metric gate passed; still no physical fit was run by this script.\n\n');
end

fprintf(fid, '## Variants\n\n');
fprintf(fid, '| variant | tag | candidate | B1 window | score | upper stability | gate |\n');
fprintf(fid, '| --- | --- | --- | --- | ---: | ---: | --- |\n');
for i = 1:numel(outputs)
    fprintf(fid, '| %s | %s | %d | %.0f-%.0f | %.3g | %.3g | %d |\n', ...
        outputs(i).id, outputs(i).final_tag, ...
        outputs(i).candidate_for_recommendation, ...
        outputs(i).b1_energy_min_meV, outputs(i).b1_energy_max_meV, ...
        outputs(i).score, outputs(i).upper_stability_score, ...
        outputs(i).metric_gate_passed);
end

fprintf(fid, '\n## Metrics\n\n');
fprintf(fid, '| variant | session | branch | points | jumps>250 | edge | failures | weighted score |\n');
fprintf(fid, '| --- | --- | --- | ---: | ---: | ---: | ---: | ---: |\n');
for i = 1:height(metrics)
    fprintf(fid, '| %s | %s | %s | %d | %d | %d | %d | %.3g |\n', ...
        local_cell_text(metrics.variant_id, i), ...
        local_cell_text(metrics.session_key, i), ...
        local_cell_text(metrics.branch, i), metrics.n_points(i), ...
        metrics.large_jump_count(i), metrics.edge_count(i), ...
        metrics.failure_count(i), metrics.weighted_score(i));
end
end


function local_register_outputs(project_root, summary_dir, best)
results_root = fullfile(project_root, 'paper_results');
current_dir = fullfile(results_root, '00_CURRENT_B1_DOUBLE_PEAK_260509');
if ~isfolder(current_dir)
    mkdir(current_dir);
end
date_dir = fullfile(results_root, '00-by_date', '2026-05-10');
if ~isfolder(date_dir)
    mkdir(date_dir);
end
targets = {summary_dir};
names = {'50_lorentz_tracking_ridge_guided_summary'};
sessions = {'590', 'n0', '20w'};
for si = 1:numel(sessions)
    targets{end + 1} = local_session_dir(project_root, sessions{si}, ...
        best.final_tag); %#ok<AGROW>
    names{end + 1} = sprintf( ...
        '%02d_%s_lorentz_tracking_ridge_guided_best_extraction', ...
        50 + si, sessions{si}); %#ok<AGROW>
end
for i = 1:numel(targets)
    local_create_junction_if_missing(fullfile(current_dir, names{i}), targets{i});
    local_create_junction_if_missing(fullfile(date_dir, local_file_name(targets{i})), ...
        targets{i});
    local_append_manifest(project_root, '2026-05-10', 'current_work_date', ...
        local_file_name(targets{i}), fullfile(date_dir, local_file_name(targets{i})), ...
        targets{i});
end
end


function local_update_results_index(project_root, summary_dir, best, gate)
index_path = fullfile(project_root, 'case_studies', 'bisb2026', ...
    'RESULTS_INDEX.md');
if isfile(index_path)
    src = fileread(index_path);
else
    src = "# BiSb results index" + newline;
end
block = sprintf(['<!-- B1_RIDGE_GUIDED_260510_START -->\n', ...
    '## 2026-05-10 B1 Lorentz ridge-guided tracking\n\n', ...
    '- Summary: `%s`\n', ...
    '- Best tag: `%s`\n', ...
    '- Best variant: `%s`\n', ...
    '- Best score: `%.12g`\n', ...
    '- Gate <=300: `%d`\n', ...
    '- Physical fit: not run in this ridge-guided round.\n', ...
    '- Candidate/path CSVs are written per session as ', ...
    '`b1_double_peak_lorentz_candidate_points.csv` and ', ...
    '`b1_double_peak_candidate_path_selection.csv`.\n\n', ...
    '<!-- B1_RIDGE_GUIDED_260510_END -->'], ...
    summary_dir, best.final_tag, best.id, best.score, gate);
pattern = '<!-- B1_RIDGE_GUIDED_260510_START -->[\s\S]*?<!-- B1_RIDGE_GUIDED_260510_END -->';
if ~isempty(regexp(src, pattern, 'once'))
    src = regexprep(src, pattern, block);
else
    src = sprintf('%s\n\n%s\n', strtrim(src), block);
end
fid = fopen(index_path, 'w', 'n', 'UTF-8');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', src);
end


function local_create_junction_if_missing(link_path, target_path)
if isfolder(link_path) || isfile(link_path) || ~isfolder(target_path)
    return
end
[parent, ~] = fileparts(link_path);
if ~isfolder(parent)
    mkdir(parent);
end
cmd = sprintf('cmd /c mklink /J "%s" "%s"', link_path, target_path);
system(cmd);
end


function local_append_manifest(project_root, date_text, category, name, ...
    bydate_path, target_path)
manifest = fullfile(project_root, 'paper_results', '00-by_date', ...
    '_manifest.csv');
line = sprintf('"%s","%s","%s","%s","%s","%s"', date_text, category, ...
    name, char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')), ...
    bydate_path, target_path);
if isfile(manifest)
    src = fileread(manifest);
    if contains(src, target_path)
        return
    end
    fid = fopen(manifest, 'a', 'n', 'UTF-8');
else
    fid = fopen(manifest, 'w', 'n', 'UTF-8');
    fprintf(fid, '"date","category","name","timestamp","by_date_path","target_path"\n');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', line);
end


function tbl = local_read_table_if_exists(path)
if isfile(path)
    tbl = readtable(path);
else
    tbl = table();
end
end


function metrics = local_empty_metrics_table()
metrics = table('Size', [0 24], ...
    'VariableTypes', {'cell', 'cell', 'logical', 'double', 'double', ...
    'cell', 'cell', 'double', 'double', 'double', 'double', ...
    'double', 'double', 'double', 'double', 'double', 'double', ...
    'double', 'double', 'double', 'double', 'double', 'double', ...
    'double'}, ...
    'VariableNames', {'variant_id', 'date_tag', ...
    'candidate_for_recommendation', 'b1_energy_min_meV', ...
    'b1_energy_max_meV', 'session_key', 'branch', ...
    'n_points', 'large_jump_count', 'edge_count', ...
    'failure_count', 'repair_count', 'exclusion_count', ...
    'session_weight', 'raw_score', 'weighted_score', ...
    'upper_medium_jump_threshold_meV', ...
    'upper_large_jump_threshold_meV', 'upper_medium_jump_count', ...
    'upper_large_jump_count', 'upper_max_abs_jump_meV', ...
    'upper_overbroad_count', 'upper_low_r2_count', ...
    'upper_stability_score'});
end


function outputs = local_empty_variant_output()
outputs = struct('id', {}, 'final_tag', {}, 'score', {}, ...
    'candidate_for_recommendation', {}, 'b1_energy_min_meV', {}, ...
    'b1_energy_max_meV', {}, 'upper_stability_score', {}, ...
    'metric_gate_passed', {}, 'overlay_png', {}, 'overlay_pdf', {});
end


function session_dir = local_session_dir(project_root, session_request, tag)
switch session_request
    case '590'
        folder = sprintf('590_gui_history_area_260506_b1_double_peak_binning_%s', tag);
    case 'n0'
        folder = sprintf('n0_PL2_10w_gui_history_area_260506_b1_double_peak_binning_%s', tag);
    case '20w'
        folder = sprintf(['no_PL2_20w_2film_gui_history_area_260506_', ...
            'highq_refined_b1_double_peak_binning_%s'], tag);
    otherwise
        error('run_b1_lorentz_tracking_ridge_guided_optimization:UnknownSession', ...
            'Unknown session "%s".', session_request);
end
session_dir = fullfile(project_root, 'paper_results', folder);
end


function key = local_session_key_from_dir(session_dir)
[~, name] = fileparts(session_dir);
if startsWith(name, '590_')
    key = '590_PL2_10w';
elseif startsWith(name, 'n0_')
    key = 'n0_PL2_10w_repeat';
elseif startsWith(name, 'no_PL2_20w')
    key = 'no_PL2_20w_2film';
else
    key = name;
end
end


function text = local_cell_text(value, row)
if iscell(value)
    text = char(value{row});
elseif isstring(value)
    text = char(value(row));
else
    text = char(string(value(row)));
end
end


function values = local_text_column(tbl, name)
if ~ismember(name, tbl.Properties.VariableNames)
    values = repmat({''}, height(tbl), 1);
    return
end
raw = tbl.(name);
if iscell(raw)
    values = cellfun(@(x) char(string(x)), raw, 'UniformOutput', false);
elseif isstring(raw)
    values = cellstr(raw);
else
    values = cellstr(string(raw));
end
values = values(:);
end


function name = local_file_name(path_value)
[~, name, ext] = fileparts(char(string(path_value)));
name = [name ext];
end
